keys:
  - &admin_gjz010_nixos_wsl age1q2gzuu8xsn2xvcqpdmftt8yyjthgrzq0r4uv952d5aj0c7v29cussp8s0c
  - &admin_gjz010_nixos_laptop age1vgcerrxut6mxwm249x6yagz9j9y86pq4csunnp3f6sc52c62yuzsdqpvjx
  - &admin_gjz010_nixos_server age16s7awqlufm0r3cj5wfhympp683aqr6t8zpfpsyxvs8vdpyh8ypxs2wh0jx
  - &server_gjz010_nixos_wsl age13n42wjj3kvmj3wk7ms3h7wgdsdpj225lyxvlutg5yd9ja5l433wqelpe7x
  - &server_gjz010_nixos_laptop age1velfazv9dlx4jqkanmcjv4hf6x6twxjme7n83nvym22txyscmssscjusar
  - &server_gjz010_nixos_server age13jmg2t7nxng36x0xqq5dvst0k9v55q733pu9w8z9xfvp9d2q33xqe4vj6n
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_gjz010_nixos_wsl
      - *server_gjz010_nixos_wsl
      - *admin_gjz010_nixos_laptop
      - *server_gjz010_nixos_laptop
      - *admin_gjz010_nixos_server
      - *server_gjz010_nixos_server
  - path_regex: secrets/nixos-cache-local-certs/.*\.pem$
    key_groups:
    - age:
      - *admin_gjz010_nixos_wsl
      - *server_gjz010_nixos_wsl
      - *admin_gjz010_nixos_laptop
      - *server_gjz010_nixos_laptop
  - path_regex: secrets/tunnel-config/config.yaml$
    key_groups:
    - age:
      - *admin_gjz010_nixos_wsl
      - *admin_gjz010_nixos_laptop
      - *admin_gjz010_nixos_server
      - *server_gjz010_nixos_server
  - path_regex: secrets/tunnel-config/client.json$
    key_groups:
    - age:
      - *admin_gjz010_nixos_wsl
      - *admin_gjz010_nixos_laptop