# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "virtio_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/wsl" =
    { device = "none";
      fsType = "tmpfs";
    };

  fileSystems."/wslg" =
    { device = "none";
      fsType = "tmpfs";
    };

  fileSystems."/wslg/distro" =
    { device = "/dev/disk/by-uuid/69bcc158-b012-497d-a8c3-a8fc3d52308e";
      fsType = "ext4";
    };

  fileSystems."/wslg/doc" =
    { device = "none";
      fsType = "overlay";
    };

  fileSystems."/c" =
    { device = "C:\134";
      fsType = "9p";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c7295d6d-75fe-4317-b048-7b6ca53cfbf9"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
