# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/27fa2885-f881-456b-b9a9-433993770aa4";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/785D-04FA";
      fsType = "vfat";
    };
  # sudo mount -o subvol=nix,compress=zstd,noatime /dev/disk/by-id/nvme-ZHITAI_TiPlus7100_4TB_ZTA54T0AB234828VB0-part1 /nix
  fileSystems."/nix" = {
    device = "/dev/disk/by-id/nvme-ZHITAI_TiPlus7100_4TB_ZTA54T0AB234828VB0-part1";
    fsType = "btrfs";
    neededForBoot = true;
    options = [ "subvol=nix" "compress=zstd" "noatime" ];
  };
  fileSystems."/mnt/zhitai-data" = {
    device = "/dev/disk/by-id/nvme-ZHITAI_TiPlus7100_4TB_ZTA54T0AB234828VB0-part1";
    fsType = "btrfs";
    options = [ "subvol=data" "compress=zstd" "noatime" "rw" ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/30986930-4d55-4c9f-857e-2bfb7cfd0f87"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp8s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
