# This file has been generated by node2nix 1.11.1. Do not edit!

{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [ ],
}:

let
  sources = { };
in
{
  "@hyrious/blivec" = nodeEnv.buildNodePackage {
    name = "_at_hyrious_slash_blivec";
    packageName = "@hyrious/blivec";
    version = "0.3.15";
    src = fetchurl {
      url = "https://registry.npmjs.org/@hyrious/blivec/-/blivec-0.3.15.tgz";
      sha512 = "iLZf17J3/p3vo7vSPo6haomLyRSiM9iQGiAPoxdwHwOB9TKf5dbDJAyYsnt4yY37JzYyMpHjZl/t11ujr3pikQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "bilibili live cli";
      homepage = "https://github.com/hyrious/blivec#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
