tunnel:
    directAddr: ENC[AES256_GCM,data:VzCUwLpkCEgA+2MeLos2mgjNgSAO7XYkDbJd0IOHY+vyk0cI/w==,iv:edFAzSC9Ls/x+TKagkcR6h0xmNUFcYRD0vcgdvBCm1E=,tag:LKS6j7kIKNU7yXZ0/x4Ahg==,type:str]
    users:
        user1: ENC[AES256_GCM,data:XgpWsK9X4SgKi0hdJ2zKANeosfy1QICEfx1f7gVBSCK5AR3/,iv:S0gK3nQep8HUWMsSNQLaCLH9wGKsMKG4PWTReWHaB3k=,tag:o/nG0zfAeKOP1UA06XMGaA==,type:str]
        user2: ENC[AES256_GCM,data:wBqFjrBGnxTNnZgn0MEKnMCit6MDpDId3csj5hyNKhOLNpBQ,iv:IuCs4yW3AjNwqTKiJQKCbhVJGjc8ZUBg1rShwoELfUI=,tag:mpI7acEiueuEL6SdxW7lcQ==,type:str]
        user3: ENC[AES256_GCM,data:rxL5Nzq/D3mfrD3HTKr8jFagZ1vC+N5ph4jLsgc7+E+MUG4E,iv:3GctPvnmiC+yPkSW6bmhDczCZo+kypH7BFbFkhNZHlM=,tag:aciCxLb+beKLF2NZeq63kA==,type:str]
    httpPath: ENC[AES256_GCM,data:MZlNIDYSkTo=,iv:6SV68iE8q0f7FRrm/IkwQ42shMA7uTzr0b2dtGGnzLg=,tag:hX6gthqnlq+eQlz/2iyW8Q==,type:str]
    udp2raw:
        key: ENC[AES256_GCM,data:El8ZVmIPM3RV,iv:RE81wgS7xcTSjPjuUsxQwwjytsqODSOZG0UKrq7Kz3w=,tag:I2HtB6pG7fyRAvFdeJlYRw==,type:str]
        listenAddr: ENC[AES256_GCM,data:9Pf9xXyslmVBUhrrTYuzrA==,iv:Xm3S5xH6vWwrqftcAdhN4lrTnU4XqhId8PyLRDcOL0c=,tag:JB9rprKxJQEORzRF0hJd8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2gzuu8xsn2xvcqpdmftt8yyjthgrzq0r4uv952d5aj0c7v29cussp8s0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYzY5MGZRcnMrZWJ2Uld6
            RGNJQ1R0UzBqSkZQc05kcENqbDRka254VXdzCm9WVno3OEZvaGtEbTJGNHFtL3Z2
            SjZ3cmRBOFpkbmcwcldoNjZ0dDZzS28KLS0tICt0ejZTTkRlT2Vwdkp6RTF6NVQ5
            VWRYcEFyai9IM3M1WW82ZnBQbTQxNUUKvWuyx8wJPbpNfro5Vmr08wQLy+pZzh92
            JgV0UHYRm0exLgJJkBlyFYLbwtoqACA7PO2ceyf83Aua/1uC8T6IRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vgcerrxut6mxwm249x6yagz9j9y86pq4csunnp3f6sc52c62yuzsdqpvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSTJZem9NdTg3WjdUZng0
            RWlERzdlSG9HeDNsWjZIY1c3R0F5R2tFMWk4CmhaZnBnTklUQVQzVDJHUEVwS2xa
            d3BRUStBQmJnblVLT0gvTE9FRTlidU0KLS0tIEtmaHQxZ1Nza2RVUndGZzl4ZHd5
            Tk0xWmlmb1RJK0p0ODFuTjVITkRJVzQKe8FkWmP9YBDRDTxqrlwaDLVUUoZToqMW
            LLWvPw0/LuV2fiuAOBKf1rGlPOO8tAy9iFCTwY+wkRE6raKR/NUgDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s7awqlufm0r3cj5wfhympp683aqr6t8zpfpsyxvs8vdpyh8ypxs2wh0jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibUJvVUZqamYzZTdTNG9q
            dUsyeXJkc1dqMHBLVXlaYzhzZitGaEVSU2hnCkVKSFM1SUNndlFZaXlUVVZOc0Rp
            WEpYRDQxU0I1QUpuZ0JRcDNINDJyakUKLS0tIFhyaFh6OUd2MnNocHFMV3ZQSmNT
            cllSWE12b21GQVdnSEI4V0V3RWFwL0UKMPQMDhP61IYZ6efh0g67oCL0RsJh63q0
            DixFD2OPCevQrZWuukNJQR6JBTnKse+S9lmyZNEDt5VNpQUUa5G/Pg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13jmg2t7nxng36x0xqq5dvst0k9v55q733pu9w8z9xfvp9d2q33xqe4vj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT1dqbitvVkpUc2QrLzNT
            M3o1N2FZbFRGSmRvTm5ZUnhlZGdteE01Y0c0CjlFMEhlL0h6M0M1WmxmeHVqMkVL
            QUVnUzZmZXljVmZVeVkzWk1nY1FZYjgKLS0tIDg0dTlxeGZYN2lVSmRQaUJmcS9G
            Y21CNzFMRmkvRENWTm4rNlUremtWOWcK7/wsLCO4fEFekHUoTHEKwgOPrTUktS/4
            3C38la6fMI52vzXd5AHGJh63yW/LuU/S3CPj+tPHwu5W6Br+PnYtPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T07:59:01Z"
    mac: ENC[AES256_GCM,data:zXbeJN7X+ZjicqAf/t7dRLnPfr+fNC8udu58ePUyvTayjItiska6FS7rv5tMyZ3a+BpqjCTeB+rdiIoDpy8VazvHQ24ZUaFvAewanbgWlHw0StKWX2avMhzXXMe5CdmVwgaQLnOncm5Osv3bYwZoEMJTOzZEFoVqPRtEpUMLuiE=,iv:jkeweiycCgVqp4EFn/kPj4xP5R2/eieno8b+DWwHL0g=,tag:0XzG1/55UAEflA0k8+FqKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
