tunnel_fr:
    directAddr: ENC[AES256_GCM,data:/X08nE0Vk9MzwL1Sig==,iv:kHoYlLomsPRbljQ5dtRDqw5cV6W+RqhK0rLZddAlZoo=,tag:y5Iz/dGreCNGKBQn3JIXQA==,type:str]
    users:
        user_fr: ENC[AES256_GCM,data:tNXnX/+Z2rk32q0vfgxK2dPiMBreKSFpfE9YQs7V7EW0gWaw,iv:onOPDkGqFK7604afVURJZ7UBolTkNW0+yv8PlvpYe1g=,tag:I0ejFF+DmJyVPPB5mSDRAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12fa2tnhpsntzy6qe9g2ugxvje26nmg6v7ekgr6wymkmjyytrhqnqxwa980
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UlU4SWNMOWNyd3JLUlYw
            UE9oSlpFUmZwWktuY05ZSFk0TTJLeVZqMUNZCkVORlVSU1JnWEUzd0xPeWlSUGFk
            NGNvT1FyZisvODJqQ0svTnZFdVlWMEUKLS0tIEpxT1pUZVlqaW0zU3g4NGdFR01X
            UC9tVTdzK05sNm9JUnA4YTRqTTdvYnMKFAGrIvk/8fhFYXrUoA6BHEpta9/WxpcF
            BMXRAga72VChtoXwQAQ47T3e60a1CI29aD8exvKw135oTiV7ivOPRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xsmhk62kql4j9hjvs0vgs86fx43husegddfzzegsvlaryu3kqssqx970z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcUVONkZVellYWDNiK1pG
            ZFlab2FDV2RJK3ZKVng1UGY4dGE5MTRaZVFZCmQwYWpzUlJtRzZ2YnZCWVNRWXhx
            Q2k1OXJ1VnpNNmd6bGxISHZCZ0VEVFUKLS0tIDUxUkF2cVNnSTJ2d3hVejZDbWFB
            UG1oS0VwVHc0MmFpREJ2d2Q3YklQSEUKrw4nPegHntEnFz/p+VC2Xch8tNfaHnmq
            tUcfkyQjqhvwv4/KGnEVmmas46HOCM5AbzmKKi/2nnVCdO/Q4g/vBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jjzm9y562w3yajyuccn8ykgac0qsd5jarulgreqxtht3kx2jw37sv48zfh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArS0h5cGdkUGNhblAvRkxH
            K2xEbFlzZXhuU1BYWVdzaU96V095a2EwZm5BCjNOckVaVGhjZk1NNGZ2SkVaRVc4
            VE9Ka2wweTFYMEhWcHBkMVVCVWk0bjAKLS0tIC9DZklLbUZVOW56KzF3QmNrV0wr
            dDdTYjlkTVIrcVMremRLYVNaSnlLZWMKGLhJmmX3F9OifbP2aLSkygcdwIRETqIR
            f711XKUEohdCc2B46LtekW3UKuoT/1MlZRiklR1zH7qnkRu8Vj0MaA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17qtkl0apngrggynk6dg6jag6hvgkud7l03em0qrwy9j7ev2hha6qenxrar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3T1lCZ2tiN2VqTEtvTFlN
            bzNCbjg2OGhYV1M1RmVrdm9WejVmKzd6MVZFClVjclF0RTNDR1NVNExKQnB1bHZa
            VElNYTQ1YTVmdHByaE9XaUloclNIS2sKLS0tIDBQc2lJUnFpS01ldm9Hc1RRcFVy
            WTZ4bGRld1dOdHRTOXc5UTJnZDFVemMKxUe6pn/gA3DpIQ50wAXS8n9oepqcmnXB
            dBDOJhfDLGqLWhCxZR8qwM30J4qof3VohqGA0bnJjQa4Y4avMSNueg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13jmg2t7nxng36x0xqq5dvst0k9v55q733pu9w8z9xfvp9d2q33xqe4vj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdzRGVTNnbWFtZm01OGNw
            MG5JOW8yWjNKcTA4UFo1aTh1OVdNeGVsZzBBCnFQTTY2YmRtM2RObFlXT0VieG0r
            VHVUS3ZkVWRIZ0NaMHBSQmhsZHNPTkEKLS0tIGNxZm1TL3pIK1F6OEwwVHFaMEMy
            SkNCdm1nYVVEWm9rUGFub1kxZHBjYlkKh3IUdzdZWiPSrlBdSyI1aAMLj4C1xjxr
            fXQdT82PIBLI9/Qmvf0DSrSBnJfMMv9tOpWMarvX9rVJG7nemiFlcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T18:31:33Z"
    mac: ENC[AES256_GCM,data:2hVff+Kx1uxTYUcva6Tw3rBduiUtYk5CyWJJwLAhDZndi9nBk10+DYbYtEsg16vYKKLunaVLYY2MOwdHFy8NtK2Ff+T2AIM+5GrcwvNr0LngqJjaNMnH4Ap8ztU5y1t631oAu9Yaka0RO3BdX7YJ/xwu4OgRJ/SN3mfGndnKlCo=,iv:JHsYxvn4AxN5LY4pG/4GfrU0xSR+uAfZSbVKMtHwiZQ=,tag:TE+vNQJP1oLpbYFpynSu2Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
