tunnel:
    directAddr: ENC[AES256_GCM,data:VzCUwLpkCEgA+2MeLos2mgjNgSAO7XYkDbJd0IOHY+vyk0cI/w==,iv:edFAzSC9Ls/x+TKagkcR6h0xmNUFcYRD0vcgdvBCm1E=,tag:LKS6j7kIKNU7yXZ0/x4Ahg==,type:str]
    users:
        user1: ENC[AES256_GCM,data:XgpWsK9X4SgKi0hdJ2zKANeosfy1QICEfx1f7gVBSCK5AR3/,iv:S0gK3nQep8HUWMsSNQLaCLH9wGKsMKG4PWTReWHaB3k=,tag:o/nG0zfAeKOP1UA06XMGaA==,type:str]
        user2: ENC[AES256_GCM,data:wBqFjrBGnxTNnZgn0MEKnMCit6MDpDId3csj5hyNKhOLNpBQ,iv:IuCs4yW3AjNwqTKiJQKCbhVJGjc8ZUBg1rShwoELfUI=,tag:mpI7acEiueuEL6SdxW7lcQ==,type:str]
        user3: ENC[AES256_GCM,data:rxL5Nzq/D3mfrD3HTKr8jFagZ1vC+N5ph4jLsgc7+E+MUG4E,iv:3GctPvnmiC+yPkSW6bmhDczCZo+kypH7BFbFkhNZHlM=,tag:aciCxLb+beKLF2NZeq63kA==,type:str]
    httpPath: ENC[AES256_GCM,data:MZlNIDYSkTo=,iv:6SV68iE8q0f7FRrm/IkwQ42shMA7uTzr0b2dtGGnzLg=,tag:hX6gthqnlq+eQlz/2iyW8Q==,type:str]
    udp2raw:
        key: ENC[AES256_GCM,data:El8ZVmIPM3RV,iv:RE81wgS7xcTSjPjuUsxQwwjytsqODSOZG0UKrq7Kz3w=,tag:I2HtB6pG7fyRAvFdeJlYRw==,type:str]
        listenAddr: ENC[AES256_GCM,data:9Pf9xXyslmVBUhrrTYuzrA==,iv:Xm3S5xH6vWwrqftcAdhN4lrTnU4XqhId8PyLRDcOL0c=,tag:JB9rprKxJQEORzRF0hJd8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2gzuu8xsn2xvcqpdmftt8yyjthgrzq0r4uv952d5aj0c7v29cussp8s0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTG91RVJPQ2xKejFjVFlh
            UkdubE9KNG9YVitKcm83Z2ZsL2NxMDg4RjA0Cm5VTVRQUi9rbElvL3h0TS9LYkVh
            VnNuTFY3ODZzRFJic3FaVkprMU5xaEkKLS0tIDF5UmZpT2ZEbEMxRWZ2OGlBZnNz
            WENTdjZPQ2R4em1sKzVuRTB6MVNMd2cKjpAjO4u2BXYEHxlMM4E/DglUPII9v9Ax
            B7Z/ZsSWi1i0gf76pzN2zlCpS+eAl692gpzSmbrOhH+VsM/wGFdTaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vgcerrxut6mxwm249x6yagz9j9y86pq4csunnp3f6sc52c62yuzsdqpvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRUlxZDJTVkhBYWtiZGF5
            UXd3QzhCNUZnc3Z1eTUwcEsydFlmTm5PNVVjCituajB4Wll0QWhUdExJK240U29v
            T1YvSUF3SE43aUlZVzJjUHZUSC9XRWMKLS0tIEhnWGRtOG0razJ6b0czTC93Wllj
            d3lxU0lUNjJYbzN6QlJXeHFoZ2xTMW8KuwUhFU2wsKqucv1LbbiDh1hmWoan4jwu
            5mnKzGyBZnnpMGeAUo3PJ+fyD3FsefY0uf75VJjstaSVk09H433nZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s7awqlufm0r3cj5wfhympp683aqr6t8zpfpsyxvs8vdpyh8ypxs2wh0jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbVpkSCtiMU05QWFSejlX
            anJ1eXNDb2VwVEtsRFViVWpvWkJ4N2NyZjFRCmlUV2lXcTFRN1FURmtUbXBBUXZ1
            VHpVTktDU28vNTF1U0Y4L3cvNnhZRXcKLS0tIENoaisxL1owVXdwanlqU3NqT3Fv
            N3lsM2ZLR3FRTVo3eWNDWTFpTG8xZTAKCTL7+UCJDu/gvILMlvyypKvP89kdz/fW
            +alumoAcFj9Fpwgx9EFjFMFr8eUf02Q2porQwM2+jYhnVf0vNutx1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12fa2tnhpsntzy6qe9g2ugxvje26nmg6v7ekgr6wymkmjyytrhqnqxwa980
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNlp6WU1OY0I4MEc5djI4
            RW91MDhCS0pqZTBMOHBCTmdZemt4bTNpdlJZCkJpaHNIa3hzNXZCV3RwM2ZZMFhl
            VUdRaVlwU01nR2pNcGRRMCttZlp6cVkKLS0tIDBocEY4cGVySDg3TGFSd3JnaGdG
            ZVdjcnl1R0ZEdk5PdlVHK0g2ckN6bncKoqs+gt+W0RUKDJJ34x769OMSgLhAe/Cm
            wvvlpTTyhdOkYBi+c0C4vSDN/RN6d1CAhYc2e4A/s+MZbiWbrOO6Ow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13jmg2t7nxng36x0xqq5dvst0k9v55q733pu9w8z9xfvp9d2q33xqe4vj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaitWeXRPeDF3NE14S21X
            TUQ4Zml6NjZVV3ZmWXYxMDVQakxTTUhYUTJnCmhBdDZXK25BMFMwcDV0aVNGb1BD
            UDFqMzlJbGJxVFhWd1Y2UFZJb0hQbWcKLS0tIC94Ump1dG0vaG03Q1o0SXl2NzZ4
            akdTRkpFcU0xcklheTRONDRZNzRhZzQKP8jxrxJsiug90BxeCTBZq0OM5NO+PHVw
            gHiDlvSnBfjuKaWucBcNCQ0pczspg3aCxJJreUCfdP2AMcQOwVpKTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T07:59:01Z"
    mac: ENC[AES256_GCM,data:zXbeJN7X+ZjicqAf/t7dRLnPfr+fNC8udu58ePUyvTayjItiska6FS7rv5tMyZ3a+BpqjCTeB+rdiIoDpy8VazvHQ24ZUaFvAewanbgWlHw0StKWX2avMhzXXMe5CdmVwgaQLnOncm5Osv3bYwZoEMJTOzZEFoVqPRtEpUMLuiE=,iv:jkeweiycCgVqp4EFn/kPj4xP5R2/eieno8b+DWwHL0g=,tag:0XzG1/55UAEflA0k8+FqKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
