tunnel:
    directAddr: ENC[AES256_GCM,data:VzCUwLpkCEgA+2MeLos2mgjNgSAO7XYkDbJd0IOHY+vyk0cI/w==,iv:edFAzSC9Ls/x+TKagkcR6h0xmNUFcYRD0vcgdvBCm1E=,tag:LKS6j7kIKNU7yXZ0/x4Ahg==,type:str]
    users:
        user1: ENC[AES256_GCM,data:XgpWsK9X4SgKi0hdJ2zKANeosfy1QICEfx1f7gVBSCK5AR3/,iv:S0gK3nQep8HUWMsSNQLaCLH9wGKsMKG4PWTReWHaB3k=,tag:o/nG0zfAeKOP1UA06XMGaA==,type:str]
        user2: ENC[AES256_GCM,data:wBqFjrBGnxTNnZgn0MEKnMCit6MDpDId3csj5hyNKhOLNpBQ,iv:IuCs4yW3AjNwqTKiJQKCbhVJGjc8ZUBg1rShwoELfUI=,tag:mpI7acEiueuEL6SdxW7lcQ==,type:str]
        user3: ENC[AES256_GCM,data:rxL5Nzq/D3mfrD3HTKr8jFagZ1vC+N5ph4jLsgc7+E+MUG4E,iv:3GctPvnmiC+yPkSW6bmhDczCZo+kypH7BFbFkhNZHlM=,tag:aciCxLb+beKLF2NZeq63kA==,type:str]
    httpPath: ENC[AES256_GCM,data:MZlNIDYSkTo=,iv:6SV68iE8q0f7FRrm/IkwQ42shMA7uTzr0b2dtGGnzLg=,tag:hX6gthqnlq+eQlz/2iyW8Q==,type:str]
    udp2raw:
        key: ENC[AES256_GCM,data:El8ZVmIPM3RV,iv:RE81wgS7xcTSjPjuUsxQwwjytsqODSOZG0UKrq7Kz3w=,tag:I2HtB6pG7fyRAvFdeJlYRw==,type:str]
        listenAddr: ENC[AES256_GCM,data:BNYwY9yLY7Ibaw==,iv:95Ch/HzvHLYzVN+4H76PVYnF+7QLdJPI4uawX2AsD/Y=,tag:TMeebZ71GGIZVAKoBP0orw==,type:str]
udp2raw-qqbridge:
    key: ENC[AES256_GCM,data:4LyLVpYMpnS4OVAP8HoetKk5GKe3YK7uwEfZHKzCgdQ=,iv:i+ylx42CPw4LmIfd3CNRlxD9wHOUj3ZUWepRS9ju4nU=,tag:NTka7XPFfpSZVlRUtyzP5Q==,type:str]
    remoteAddr: ENC[AES256_GCM,data:boA0AxMYI7hCiVT1Og==,iv:maZDpKZV8zVdlB8Mb/0W6MpuLhVTLJJsGvxt1/1EmuM=,tag:Oy8ez+yYHXaLfrABnOsTbA==,type:str]
    kcpKey: ENC[AES256_GCM,data:aDx9HZS2hIrBrkJxSbYr8bUr+lNj5Rc08L+AutV2rpI=,iv:D+qUhE3YBBWpJzf7A6lrOyO3TblKghgKFO51D0Qelck=,tag:QovEzNg3RXtIr1H0vCAxcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2gzuu8xsn2xvcqpdmftt8yyjthgrzq0r4uv952d5aj0c7v29cussp8s0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bml6bHpnRCtCTDc5VmVL
            UEFlUGVzWFdqdXdlVnh3RjQ4Rk8wV04wMEhnClRmQWxOMG4vcnI3R1hYWmx3cHUx
            K1d4dGw2Tkt2cGNDajJFNnQrdmJwdGsKLS0tIG5xVk1FQ0hKbkJQU2c4MjRqUXk3
            VUZkUFMwVy9Wd09ENUR1K1J3MlI4YlUKsK6Qv8XbC9RZgaM5DbXfCm4o9PeJAVF+
            qea8WowqE7R9TThJ8NkhlX7cFRoXHcd0ZPX1Zz/tbCM2WN1eaC1ubA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vgcerrxut6mxwm249x6yagz9j9y86pq4csunnp3f6sc52c62yuzsdqpvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabkQ5Nm96R016MGQ4eVR3
            RENJdUlaNjRXVkYwZUt0YnZIWWlHTVY3UFRzCmhKZlBQWnY3V2JaV3NqR1dtcjN6
            cnBKOUlYRkRCTmtLUk5mSWQxLytqZVkKLS0tIHpKVlZ1RXdiSFBQenR3SVhlWnI1
            Y2pLK1BpWGgvQk5ROG5Xb1pVRU5FbFkKLyPZEVdz1+iMhf7I8uftAwGTGMkkpJw7
            hg/0RDbMM4Y1CEY0V1juiQHwy+vkW5/QFDanj7fvRNOJO0/FbsRgyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s7awqlufm0r3cj5wfhympp683aqr6t8zpfpsyxvs8vdpyh8ypxs2wh0jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQzJIUVdabURKNktNSk03
            a3lzam5hdTZWZld4MVJkOUIvQndTMFVJUUNNClFwUk9PVDR0UENGZm5WeXFHYXVm
            cEtjNUdOcUVTVHBpNDRjR2t3TklFY0kKLS0tIEFNQzh5VTl6MmUydzk5ZDF6dHdt
            MTZBV1hiSzhIRTlYeVhlbjRQendMWVUKc7xQ7xD6sfw7xD6vezlPIkvtbrYbJnSA
            3s18Ew4/UoOmEhQQwDhfBTZoyqF0b6NNG/1oTgZme2Gj8FVw4SFbRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12fa2tnhpsntzy6qe9g2ugxvje26nmg6v7ekgr6wymkmjyytrhqnqxwa980
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPN1l4ek1OSUluQk5GMlpi
            KzF5azVSRzE3bGg0dnpkeWpvYWZCWTF3SzB3ClgxUE1WL2dYTGc2S0NSSFo5cXkw
            ejhJdUE3RWhUbTRNdHk2b0hoNFNwMlEKLS0tICtlbk15MWFlNG5hRU82K3VqMGli
            Rzh1K2s3Q3NMLytncER1MTNKYWtSOFEKsnWFQAZh5ztJrzm8Ednhh2puz1k9/Dfv
            uTYHY3TFZ4LqSQMiXE3FABw9J+c4RbigolFKNO3V4wpnTl/xTuIc/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13jmg2t7nxng36x0xqq5dvst0k9v55q733pu9w8z9xfvp9d2q33xqe4vj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOXFPVjBnNTcwV1p2YUdo
            Rit2amdZME1yNmYyWjBDQndzWndheXlFaGtnCjBkeS9UTjdtcHBNaEZXOEFZWHB4
            VHhnclhEV2FYSFJLdVFSbUlvQnFFemcKLS0tIGdHTGt2UWZtWjlKNlhSNTBzdjVv
            TllxMitWQ0NZS0hSTWlHODBMYWR0amMKolqfPLKiwU423AkYrZffH2YYVhJUAC3h
            pWmWAE6IqHwYn/BANd5j7AdSkQq1IxFXJ/w9V//fVLAJ/S16QDGvIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jjzm9y562w3yajyuccn8ykgac0qsd5jarulgreqxtht3kx2jw37sv48zfh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV051MzVkNENnQUcvWEJD
            eHhGSE1hanNlNGdNZnZkbFBsOEk1cDN5eVRJCkZLeWNod21qaEZlM2dVdFErMHJ0
            R1FDUWNudVlCVFgyQzZmZ05SVGxaS0kKLS0tIHdUMzdUcEVORzYwNFlYZTFFVmVn
            YmtIU002Smt1a1BBRGpJTXNieUJyY2MKSz5h4jtq++DESFKqiVwbpLIuUGEjkkPo
            wB373IhIqkwBA/MZwetYF//FHZNImRiFnL4jLNfAJ4mwDic7+zlT4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17qtkl0apngrggynk6dg6jag6hvgkud7l03em0qrwy9j7ev2hha6qenxrar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N2k1ZHF0dTJIV285SmVT
            WVVTRUlLekQ3alNJYktpSmJISXhEQ1VxU1dBCmswLzJqUkIveTdXdFhia3hTSFhT
            eXVFN3YrS214b1V2MzVueWVYR3cwYzAKLS0tIHV3ZVZ4NzRHRnNrTTEwcTZhTEFm
            USt5UFJjcllOZmJnbkF5d24rcHNDTm8KemyeVZGinCn6P7EL9NuhxtyLAMK/EvbV
            pbftj4zH4Ozx3ZrSYc4g2PNJnzW04rWPMWHrBPVrZfs81NSXFUcKeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T16:28:43Z"
    mac: ENC[AES256_GCM,data:BVzuM0nbkU4vnenRTbv9FPezrP7nX8OGlD0DP5wuqg6h7JJsESckLQaZAqUS9jHtgf/wl9rMYOwK3jpM7svtL82nFTM4++0SVvyvsbyBY3HyMD/OVn87mGqkVYwEyC/Y6U7LUzcOSVU8DZIFDaKQsLgJ7KBqj1J9TTNiZyFAc+k=,iv:jfMZ5InrrmUQ75DdiHNCc51aECrqlEsCPY7EvU9qZvc=,tag:QgX94qgOHMdWsTFKzO3cQw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
