#! /bin/sh

# variable
# xresource
xrdb ~/.Xresources

# restart sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &


# authentication-agent
# /usr/lib/polkit-kde-authentication-agent-1 &

# fcitx5
# fcitx5 -d &

# picom
# picom &

# polybar
pgrep -x polybar > /dev/null || polybar &

# variety
env XDG_CURRENT_DESKTOP="bspwm" variety &

# dunst
# dunst &

# disable the ugly "X" cursor problem
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zotero:*:"Quick Format Citation" state=floating
