# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ccc04210-56d1-44fb-bcf9-7aab4793154b";
    fsType = "btrfs";
    options = [ "subvol=rootfs" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CB4F-00BA";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/ccc04210-56d1-44fb-bcf9-7aab4793154b";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/ccc04210-56d1-44fb-bcf9-7aab4793154b";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/partition-root" = {
    device = "/dev/disk/by-uuid/ccc04210-56d1-44fb-bcf9-7aab4793154b";
    fsType = "btrfs";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/9be751ca-b5f3-4947-b2a0-4f1e3952b268"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
