shadow:
    gjz010-nixos-wsl:
        gjz010: ENC[AES256_GCM,data:BhnnYikPDJ7fWyTkInQ6VMxdGH+iuTlprXpQGyRJeortNLXhwkgF14Oa9rlCd1Qs4bfxbVgfrHQIr6letkR9+yS3sqmhBVE6rw==,iv:wqZwRwJ7Rk8Dn3g2m04pVBlZH5cybKjgShPqdsfFBA0=,tag:/lNo9HpkbBZBMUjOKejkDQ==,type:str]
    nixos-laptop:
        gjz010: ENC[AES256_GCM,data:+cUTKdfopdPa0jy34KOS+IiHv7CXSBovFNArkQ6bZt+Xgam8bLPVOgOS4g0cD8x2S/1P4kX9cjyF4FbveSBSr75Cy4IMCc2VmA==,iv:aHW+Z+k9BeEb4HlJJvTs1Sw6Trs1p/MW5Pf0svEeFg8=,tag:0bVlNW/uT+4nsN/XceZMLQ==,type:str]
    gjz010-nixos-server:
        gjz010: ENC[AES256_GCM,data:NFjSrHaj+bKkRlHwmZZ2oq+z63AvSMA85vxqMqEtFulTRrxZbBcRQjJAx4GDLLOyADUOoq7ytfAj9cagNU++TGgKEwatD/5wbA==,iv:o7m+R2U/r43r0qPwIOtDpZV/lrXMtOAltlufsgfvrrQ=,tag:1uO4yfoC2ea0fKEV7PSgAg==,type:str]
    nixos-desktop:
        gjz010: ENC[AES256_GCM,data:RyYUiYvyv7jZ8M7yA1mNPSGhHji2DTCxk2l/Dbr8I/Y1+mufFHZUaSg4PDsaAxzB/cblw1Ob+m0CDP62b43XDMQCB1p3U1g6sQ==,iv:tdiYVcJ3WJuhYUl7CHnNeQpsW47S8HKN4VYuDV8jaA8=,tag:xviG4SkCQC2BAvDJ7ptsFA==,type:str]
    gjz010-nixos-box:
        gjz010: ENC[AES256_GCM,data:ovPo0MUefHDat/r3oqcgcpBS6j/89WxueOW+5yEu+1VwsOnLos4G3Fr74kofzokwCCN3ra3RIWbR/qPb2RpK3dfjmYjZukMqYA==,iv:tL5ylqb6Mm/XaywgsdtQY04Q2w31z8mXxZEOH4GrEqU=,tag:0zKMi3f+AgypLac++N3dLg==,type:str]
    gjz010-nixos-pi:
        gjz010: ENC[AES256_GCM,data:Mnp4HfUvfk9rjnZ9uL4ovPOfvwdeApUqT6Szj4ExlX5eeGy7SgrS3qu5HszGzKq8NTIg38JgPIF33pzvh8P/9IbzAhqTl4rgow==,iv:EGHFdC89zxhIMEFSPTPtt5wIMvJaevYcB+3f6vXRMRI=,tag:36PFqHXSQH2q0bFXIttPjA==,type:str]
    gjz010-nixos-miniserver-fr:
        gjz010: ENC[AES256_GCM,data:qNXfqskxjuD+LnN8mbK0ndtnccFggbKkXMKnIOigEJIMrROZRjslR/WjiQpcirwXT76qgXKm3aVE3JdonZl7JuTVPoJPL7GqcA==,iv:dNjGHqjNwzeS47esuT9CU/fPvNC1oT3XjltDFvRjvsA=,tag:L++jnJTTQ2hFJZxIGkH8lg==,type:str]
#ENC[AES256_GCM,data:yqzst8CppA==,iv:k2UumlVv/zfAKwzXV2kblWhsMWuLdnKWzw/2iZYv9eI=,tag:U5m2XgRs+cMDIHFfnk1fLg==,type:comment]
#ENC[AES256_GCM,data:lBK9q0kS6u9J9UKLzzpActDsXR51MnBPypPBvpj+lg6A92jY1XYqYHNOjsjFdniP3sojbZg=,iv:SfXyanYoHdS+YbI0Yxj3Uho7yCrsrua0v12e0yVZ0l8=,tag:uYN0q3cK3WWv3y4m+5lc5Q==,type:comment]
#ENC[AES256_GCM,data:KCFTMa0qtuJZFw==,iv:xQJvQo7aTOiFLIvMZU2/gVNSJRXRLt7jYuMy9O6ToJg=,tag:v5loYxvk5PYUCqqMAOBQmQ==,type:comment]
#ENC[AES256_GCM,data:D1GG+0v5bjiIOKimVg/U547v/7K8ysZ4TrWEBzJ1w06jlg6UWOTboy8YL4gCKvSazTQN,iv:6DeJuFJ8KwCgNsYBAX6Ao4QAT5qvguXhfUpxGcPhrSQ=,tag:SqnquN+CGc0zNWbv16MbxQ==,type:comment]
#ENC[AES256_GCM,data:5Vy+r4DQmOxzp94rYtrGgxAEP6lTfpJMeHibuEsYG8nZk8KAVgWZzU5ZFeCy1hiiVZF1,iv:ymvGt7TjKsBodp9TAkxrqlSHDXPyIHK53d3RdmjMng8=,tag:kjqqK4LtE89mBjIUFWv4sQ==,type:comment]
#ENC[AES256_GCM,data:jPWa0azM5nlmwJIZgZMVO8Fn9QFqd0joHUt4kQdirAhS14bal23JQbgETWvpgbcdgfLc,iv:Caung2mLx2CPBsWQgGCw1ntqIEUBnDDE4cSLIf71Jmo=,tag:uU9KcbWFiTZQEmLTdBe/BQ==,type:comment]
#ENC[AES256_GCM,data:SbHWuYggACxhyIrZyRoien7PYZMyrA==,iv:ACe0L8oi5mm2cCvzPsY6+E7MyMexNBfeu9rraJeBEv0=,tag:h3oHKOWDvs9somHwUafBJg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2gzuu8xsn2xvcqpdmftt8yyjthgrzq0r4uv952d5aj0c7v29cussp8s0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQXBidXFaMnJFanJQaWUy
            QkF6L0pWSWlUckRzd0hBSjNCb2R1STBjV2dvCjJyOHhLOGRrb1NOUHJsckVVdnRh
            cHd3VUE5dEh5TUZ4d3NYNFlRdFdQSjAKLS0tIHliVHBBckorS0ZBVmE4MElPWmV0
            NWhZODlPa2ltaDM5aWs4a0JUdXY5anMKer4bgiFzKe/9KDEk3LN8DYdJMXARgJGk
            Xlo+XrnGPIT5u5UdComl7wMy58Wr+b1vS3QuYuqis5bfXs29EQmZGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13n42wjj3kvmj3wk7ms3h7wgdsdpj225lyxvlutg5yd9ja5l433wqelpe7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmtickIwakNMYjYwY2dE
            d3kxOFlNTk5GU0JFZmpXbmpjemxENFVwS2djCjVTSkVvSklFYUorQjVoZ01CNFV2
            OGk5aElpMmdVYmN2eSsrZHlWZzZUL0kKLS0tIExJaFBmeHhtakZVYk50WEdLWHZK
            cDlIZ09NYUZLTWlucUJ0Qm5KdXF2MDgKAa1eUMDUkadwYYJGnYs6SNsRMnAt367i
            7/oY7VLIVh8rf3HDEpKNu2SwcACgex1HRQop8zzOLzsFbc9jun+yFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vgcerrxut6mxwm249x6yagz9j9y86pq4csunnp3f6sc52c62yuzsdqpvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNklaSXFRUU9XNlhteTNu
            U3Q1TTZhOWhiUUdvRTJuZ2ZadWlQQktnL1JFCkprb3lwRXptMTQycVk2VDZ0UWtz
            T0d2ejhFNnp6aDU4RzEzVDB2ek5FZkkKLS0tIGlBVHBRaEpaQ0prZ3g0WS9maTdM
            Qk5odkg1Z2d2eUppOXREZU9TbW1UdzAKndgz+xBkHlarFto90aAV8SgYDnPeIbVf
            RIL+GMYeqR+HkLXAdQ9CCwnITaL2fH+ydNmriOw0j6tMBEextU60CQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1velfazv9dlx4jqkanmcjv4hf6x6twxjme7n83nvym22txyscmssscjusar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUVdhaTVnOUdDRG95eG9W
            Y0JhU3JSVnF3NkxNV05ORHM0UURqSUxjaUFnCldTa0UyV3cvbm81ZzJncnpFTGRm
            a2Q5VGhGNkU0WTRjUWp5VmVJS3ZjQTAKLS0tIFNZcHl2RFdCQVJUN0pyUGUzYmpi
            ZmJucnhpK0VJc0JGYVh6RDIrRDNIM3MKeiK0ZhdXqo7klRhhBMTibgS3TrvxaDP/
            z8lgf5B5H6Im5Z4cLc8rA19JxmUau0c+HxYXE+B4Xj1TPvdQv77J+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s7awqlufm0r3cj5wfhympp683aqr6t8zpfpsyxvs8vdpyh8ypxs2wh0jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NnA4bjluQ2JETW1Jc09y
            SjRpaHVNT2ZaMGJkS3l2UW9UU2RmQUpBcVNvCm9TdDdtRFZRelZObUFCWi9nYlc3
            VXFDelZVV0xMS2tVUldnU2FOODM0bTgKLS0tIE5yVVV4WERxVVFYbDI4VGpML2xI
            WGVHL3FybWZhUXRhNG9HMXFtNzUxZ28Ke20BZwAOkHaP1Wl0QRkWy/rlwlrItMSz
            uibYoPm9OaYPNx4VqjHJqWM/L/ttZoPzi0kiKoIYpVT+zcaeMYGGgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13jmg2t7nxng36x0xqq5dvst0k9v55q733pu9w8z9xfvp9d2q33xqe4vj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYUFsb0s1enZwMmJhSEFV
            akFMUjRLTWFtb1BTOGRTaXB0MkU3UDdLdWhRCjlCYmRacXJQRFQzVlc1cmFmenN5
            V3RSSTk2eDVHcTZTcEZBTVJKQTEwRTQKLS0tIEg2QTVFQnB2UmJSVThNVkVnMXhI
            ait4eHJtRUtpajE4ZENRTEhiK0JvYUUKdkZufeoK8p+gLE8YlrLzptBc9jGonQOi
            mS3EKWPyKlc2tH1itF5Jm2c4jUOxsTcIZbwRpNfEflw3yNJ0AMojlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12fa2tnhpsntzy6qe9g2ugxvje26nmg6v7ekgr6wymkmjyytrhqnqxwa980
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSVV3dUVMQlhKd1ZINk0y
            dnVOZy9WWFpYZmcydEkyazcxL1ZJYUhvaG1VCkFCekoySVR0WEg4aXJQeGQvN3Ux
            VHY3bWJPYUo2RVJvSjJuUTFrUW9nVjAKLS0tIGQ2TCtKbXFjU3V5WTlPOExObElY
            aXJrSU1YbnVEUjNmU0MwSG1sVEYwUVEK9a0/VUv48g5iC5rE2HakgHro55z/J8t+
            sut4Hcw7FszBYtfi+buE19xNeCHc1hYsRmuW5qtuhlU5kvGiIM/cyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nd74ktldahmyq9x8ycc4d6em37csgp4mfm84rk87vsmxxd7d6ydqalv8v4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N29XM3NZcW8yVFZHWkdl
            RSs3cTFnd3VPVTRvQzV2WkhTc0c5QitXM2pvCmtacVFodVpwejlMNGVwRHF2aGlC
            RkJmcW9icUt2ZHMvZ3c3YlZ0d3pnZzgKLS0tIEg2UC9OekJSYUQ4eitUeGpGUVBy
            bEJmZzkwZ2VudmJxY2hDQkpZVGcrcTAK2juR1fdCcawLQvhDoz905xNkcuNcbEz8
            y2AdBGSM3bYjieSmCzha69oUbIz145fTvjVPAP3D252w0u1bTwY6iQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qrvxhwk50zkas9u06cauxlhtwn2hh9cj878nl0u8aae64pkmdves4r8dwz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUlI5T2RXQllJZnpjQlVV
            VXRGaUFjV2FxN2R3N0NJRXpXN3V1RytSbmxJCk1DUXA5c0g0VzJxTW5KV3BqWVlV
            bWZhbytIOWRXYXBlWUkrWmFVdEUvcncKLS0tIDA0MnhtaUZTNkczbytJc1pmRUkx
            bldieHdyZWxySlk5VWo1VU1qU2w5WGsKRxv2fQweTizlnIefjiaRfhkFAAD9I8+v
            zSRcjYAl+E71PcQuz4zDMdI+VPtWnIg+vBZE5IzVTWqn+PxSCOB/yQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wl8npxnyfd6vllvheqqgt9fqygerczrpmfsnlp7w7x2lemfd9f5qzltda4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBId2FtRjZYZzdDQ0VzRTdh
            Ym4vWkhFT3Q1UC9haUxlYWNzdGFLQ3pJQjBzCm1PRXhWZS96YWxvRzh4YURaaURG
            MXFHVlNNa3VJVUV1Z21NbTVCdGk0MUkKLS0tIHJIN0VvaDF6VDlsQVZ5ZmRXL3dM
            cWJUakdxNWxjbFhPYjlyOCtlS2NjQ1kKeFOILHgm8vfGc+fmYw7LMCZIpx7blziP
            oMWUc6guH5nXtLt8sHLOz0mNK8m7+PltxksmY0yiXAItbPBeZiOsLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jjzm9y562w3yajyuccn8ykgac0qsd5jarulgreqxtht3kx2jw37sv48zfh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkemhWZzZCeHRDS1BZcTFX
            Z0V5Mm5aeGlpZFlFOWo2N3NsZ1dXZmo4Snk4CjlINEpnMkdUK2l5djVwNlFUUXNH
            cC9aM0VndlRySnlRRHQ5NUlSRFlpU28KLS0tIE5ZTzRSTnBZRXVVc0FrNmdsY2pp
            eDdZQWgxNnpqeUNKbkNJMjZyTmtOUVUKhpMxXA8iXj2hpHzMZhyCaFRFte/cEHkt
            k6zA+a67q2TLEi4sMevCPo0tQCZ7Ko+wBW6zc2KjfnrrPWrT/RNVIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17qtkl0apngrggynk6dg6jag6hvgkud7l03em0qrwy9j7ev2hha6qenxrar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNFdBOFUvdlVmVm5ZenJa
            Q2RMQ2xSQVo3NmFRckZVeE9iVGNIbWowdTJNCjBhczhyaGxhUytYRG1KdnVPNk1H
            M1VpUlZSTllGdDhic0JPbHAxVCsvc1UKLS0tIDJGUzhEd1ZJN2NqZVlhMkFzM1JV
            V3BEYUdtUkQ2VjdMeFdTaUdQcXM1UGMKZ4zwYuPPZTT8LZ7a/iPfdsxoAtx2UrOX
            U9Dz4nsNHhpWt3LHh6c7NcQmwalViYUpkK6OT9ywfVLyZnzs5csL5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xsmhk62kql4j9hjvs0vgs86fx43husegddfzzegsvlaryu3kqssqx970z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTmRpNXNrR0J4bGNtb3FO
            Tk9tSzV1UW1rUjkrZU1KZFZDblMxVWs4VW00CjUyR1lSNmxDdXoyS3hjekFnZytK
            cW42VHMrVnBJQk5PcEV5bm9RQ1V2ZzgKLS0tIHJoRGhBTW5ZK1ZnNFBqbDdzNWQ2
            UndwWkR1a2p3ZUlsVU5QS3VrYXRtODgKb2M5NfV/F2ntQosGpulSj4dsolvSiYgg
            ZujlRZogMJNSYoH9aZvTGLM03vBgTWYWkHTNMQNzRM9YzrwQinYojw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T14:47:13Z"
    mac: ENC[AES256_GCM,data:S4EgmPnbFsAZVHtkodQl+bm6E5q33dIwekWVd0dhxIOT7SHcP1rD+J3PLGLgFS0oDhkj+PtAkuRjs8jZUCBFeh59gd1yIMCqzd7rgrF6jA8vhdIglzh5HQ6tewIfMtEOB8IEkOVsBJwBP3ND0zhiy+0NdFS6PVfLeYeZ1VadB0I=,iv:VVIasuEeYop+rzBbG5JPzVaMx3FBeFLUANPK4LqMizU=,tag:kbpC25cPYre9HOWndvgJfQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
