shadow:
    gjz010-nixos-wsl:
        gjz010: ENC[AES256_GCM,data:BhnnYikPDJ7fWyTkInQ6VMxdGH+iuTlprXpQGyRJeortNLXhwkgF14Oa9rlCd1Qs4bfxbVgfrHQIr6letkR9+yS3sqmhBVE6rw==,iv:wqZwRwJ7Rk8Dn3g2m04pVBlZH5cybKjgShPqdsfFBA0=,tag:/lNo9HpkbBZBMUjOKejkDQ==,type:str]
    nixos-laptop:
        gjz010: ENC[AES256_GCM,data:+cUTKdfopdPa0jy34KOS+IiHv7CXSBovFNArkQ6bZt+Xgam8bLPVOgOS4g0cD8x2S/1P4kX9cjyF4FbveSBSr75Cy4IMCc2VmA==,iv:aHW+Z+k9BeEb4HlJJvTs1Sw6Trs1p/MW5Pf0svEeFg8=,tag:0bVlNW/uT+4nsN/XceZMLQ==,type:str]
    gjz010-nixos-server:
        gjz010: ENC[AES256_GCM,data:NFjSrHaj+bKkRlHwmZZ2oq+z63AvSMA85vxqMqEtFulTRrxZbBcRQjJAx4GDLLOyADUOoq7ytfAj9cagNU++TGgKEwatD/5wbA==,iv:o7m+R2U/r43r0qPwIOtDpZV/lrXMtOAltlufsgfvrrQ=,tag:1uO4yfoC2ea0fKEV7PSgAg==,type:str]
#ENC[AES256_GCM,data:yqzst8CppA==,iv:k2UumlVv/zfAKwzXV2kblWhsMWuLdnKWzw/2iZYv9eI=,tag:U5m2XgRs+cMDIHFfnk1fLg==,type:comment]
#ENC[AES256_GCM,data:lBK9q0kS6u9J9UKLzzpActDsXR51MnBPypPBvpj+lg6A92jY1XYqYHNOjsjFdniP3sojbZg=,iv:SfXyanYoHdS+YbI0Yxj3Uho7yCrsrua0v12e0yVZ0l8=,tag:uYN0q3cK3WWv3y4m+5lc5Q==,type:comment]
#ENC[AES256_GCM,data:KCFTMa0qtuJZFw==,iv:xQJvQo7aTOiFLIvMZU2/gVNSJRXRLt7jYuMy9O6ToJg=,tag:v5loYxvk5PYUCqqMAOBQmQ==,type:comment]
#ENC[AES256_GCM,data:D1GG+0v5bjiIOKimVg/U547v/7K8ysZ4TrWEBzJ1w06jlg6UWOTboy8YL4gCKvSazTQN,iv:6DeJuFJ8KwCgNsYBAX6Ao4QAT5qvguXhfUpxGcPhrSQ=,tag:SqnquN+CGc0zNWbv16MbxQ==,type:comment]
#ENC[AES256_GCM,data:5Vy+r4DQmOxzp94rYtrGgxAEP6lTfpJMeHibuEsYG8nZk8KAVgWZzU5ZFeCy1hiiVZF1,iv:ymvGt7TjKsBodp9TAkxrqlSHDXPyIHK53d3RdmjMng8=,tag:kjqqK4LtE89mBjIUFWv4sQ==,type:comment]
#ENC[AES256_GCM,data:jPWa0azM5nlmwJIZgZMVO8Fn9QFqd0joHUt4kQdirAhS14bal23JQbgETWvpgbcdgfLc,iv:Caung2mLx2CPBsWQgGCw1ntqIEUBnDDE4cSLIf71Jmo=,tag:uU9KcbWFiTZQEmLTdBe/BQ==,type:comment]
#ENC[AES256_GCM,data:SbHWuYggACxhyIrZyRoien7PYZMyrA==,iv:ACe0L8oi5mm2cCvzPsY6+E7MyMexNBfeu9rraJeBEv0=,tag:h3oHKOWDvs9somHwUafBJg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2gzuu8xsn2xvcqpdmftt8yyjthgrzq0r4uv952d5aj0c7v29cussp8s0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEblZTMm5JZTVUMXJBYm85
            cmdFSXovRXk3RFVUMTZJMlZ3UkxNY3YyZlhrCkJaMXdlVVVWWFJGOUFOOVd6STJz
            QXhsYWtubnRPSVNXYzRFWjk4RHhhL1UKLS0tIFlNbklGNlM1Wkw0ZklvZFQ0ZGhY
            NUlXYnloNXNUbzZEZ1FKclN6QlJ1T1UKHTUvdM+QYPGfcmUr4qok7qyo2QvbEpaX
            QDunW8/ZRd1mM6ofVUMD5O+OEakXK8y920Lcu8nyDqtD+tGsvcHq0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13n42wjj3kvmj3wk7ms3h7wgdsdpj225lyxvlutg5yd9ja5l433wqelpe7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6M0tzZUJEUzRISFFwckVQ
            S0FvYTNsK3Bmcmc2OUVrUGRZZGZZd25UWnl3ClhUd3FXbWduekFwNUl1dzhDMXhV
            SnczNGx2bm0vOXhjNlU2dHJCalJXQXMKLS0tIGd6bktoSFAwUmNEYVFpSFhyeUhI
            TW1KT0tETm1JMzIwRCt4VGR3SVRBVFEKX1iw7QcOoW2Ni1phzq37gJuyTTmPMxwz
            j7AhEl5dfxtk4oTOBkIA7EMcbxBU2bI/7f2AmkatzbpDBpkO9e4BFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vgcerrxut6mxwm249x6yagz9j9y86pq4csunnp3f6sc52c62yuzsdqpvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvanMrOWZhOVJkWkZnVUpH
            QjhUNzdOTlJoUlZYSnpwR1hOMWJ0MVFQeEc0ClRXRXpITyt0d3lvM243MGlJaGRT
            cWV6QzI3TFBYMlkyYjR1RWt5QTRPK0kKLS0tIHBZUDBSQ0lDNHZ3TjJVcXVDTXRt
            UTV0cTlGUlRIWHVVOWZFYkNEeUg3OFEKXCBMlosAZYjf0+EnwmEs58pETKoX8RuS
            KvcXGNZnzXd3zXKufOUOngKwhHFJVs98gO7rIcWEPFoKTrPq6y0jrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1velfazv9dlx4jqkanmcjv4hf6x6twxjme7n83nvym22txyscmssscjusar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWmlmNDl5ejNFV3o5cHFN
            aExlV2lxK3FsQjlPSTVHVWZoTHh6eWpGMVhNCkp5U1ROa3dMRWRsd2VFMmJ3RUVk
            UGVDdDB1MVJRbmhFTG93OEh2aWp4TmsKLS0tIExKVGhrOXhJazFPK0hqQzB3ZElJ
            M0JKaEpDbUF2VGw3OU9zVzFSakpoWEEKob6qr9/8kMnKdH6Tbm7sCWLr/5H62GcZ
            WDmUCQtovOONTOKriaukp0F4L78QFRGa/oMLoOpZpzaVuRYwF3T2Wg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s7awqlufm0r3cj5wfhympp683aqr6t8zpfpsyxvs8vdpyh8ypxs2wh0jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLc0NGQXhVYTB0TFord3Nm
            aW5IczY4YjVFYmhSanpOVHRXWlFPQnMwamtzCjlCdm5MYkkySHlJcG83UzdNNFFj
            ckdXS3JLQ3RsS2NnSFNSWkx1L045SDAKLS0tIGExVEFOQ0tzK0IvNDJrQWM3VVpG
            VTJTUERJeCtPV296SnhyTFJlN2F4NDgKhgEtxZBkZ7V18tGAPaXAIHGp3VrmzAl3
            KfuUDn2LpVS4Wbwuxp8l+sPdrUUX0qtZ6I8GJYlpL8OJAIdppIZHGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13jmg2t7nxng36x0xqq5dvst0k9v55q733pu9w8z9xfvp9d2q33xqe4vj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN0h0d2xKaWJMWkdhUHVl
            RkxvTjlVbXh0U21sWEdVS1h0S2psUFRHbmpnCmw4YkRZVG16eFBYNFFJSTRZdUJW
            VmpkMmgrL1pxak9uazlNRWd6MTRzdW8KLS0tIG5KMWZ6U2VuREF1dXZKS09xSit0
            SENoSXpmYlhrMnNBVnFiZ3VZZjR6a3cKFeYQtTK1BfVjKFLvSZEJbk8TaXYYCBGQ
            YJCFWMw+wQp+HUYD1KaxeC2Ubtqqx5angZ19oijkwNnZiWJwF2wsQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12fa2tnhpsntzy6qe9g2ugxvje26nmg6v7ekgr6wymkmjyytrhqnqxwa980
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUnpFNmIxc3c3Yks3clV2
            Nm1xNDE4a1JWSE1DbkxUNDlVeVpYVm9aN0hJClZlZkpDVittVEo0cVZMRGdTaWMy
            TDduV1FrZk9uTVpqV04wYUlNbzB5VVkKLS0tIG9rSHNHdEtreFFmcEhJMWVQM3l3
            bzI2N21maXpkS0lmdTdmeDZGRTBLck0K1+s0w1jwCVYSA8+J+qK7XVw3Sc+ZI0i8
            kK3hAabzQMA23EjSVdG+9pAFi2JawKHs1q40kB9hvqRbGxDyE5nmdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nd74ktldahmyq9x8ycc4d6em37csgp4mfm84rk87vsmxxd7d6ydqalv8v4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWkN3TU9QVXNXTjhxY0Rz
            ck16VGcycnJtQ1dZKzRHZWdtZ0VDSE5PL2hVCnhiWjBUU0ttWE1FbVFYYWpBZGFq
            WlNiZG1pOCsyRDRuMkQ3bkRjQVZMb3cKLS0tIDJDemcrOUNmaUUyU2NjMStJNC9L
            MkJqYVpMMmJtUUNnYWRDQk9xT3ZYNTgKsUVV511Vti9XAjJwTZcWsoDjJjhmkq1+
            RWldSyd6/q12V6N0eSyyOR5GXnk9wCdEN1zseDGAoz/5ohAM9RqWJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T07:53:04Z"
    mac: ENC[AES256_GCM,data:oDJXbT+cdpB7YpIfXjvri85a/08glgcml3ZMldxKr91gJflE8H48bOR/CjOrHCs53vkbCtxBl7OJ2LSqV6Ufq/YbUz7Ph+3Q/xiHtrf4zpTQLeMcW5Qw1XRS73kOBTw3ReUIm8t+sB7YGbLkhnKk2RU7ecyaXe3LwuGCQOBZLo8=,iv:EkbnEnkoJZOAA978HGoB9m+BWAijRskluXgdTwI9sy8=,tag:fOAxLx9IlcnT8Wath1hJzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
