shadow:
    gjz010-nixos-wsl:
        gjz010: ENC[AES256_GCM,data:BhnnYikPDJ7fWyTkInQ6VMxdGH+iuTlprXpQGyRJeortNLXhwkgF14Oa9rlCd1Qs4bfxbVgfrHQIr6letkR9+yS3sqmhBVE6rw==,iv:wqZwRwJ7Rk8Dn3g2m04pVBlZH5cybKjgShPqdsfFBA0=,tag:/lNo9HpkbBZBMUjOKejkDQ==,type:str]
    nixos-laptop:
        gjz010: ENC[AES256_GCM,data:+cUTKdfopdPa0jy34KOS+IiHv7CXSBovFNArkQ6bZt+Xgam8bLPVOgOS4g0cD8x2S/1P4kX9cjyF4FbveSBSr75Cy4IMCc2VmA==,iv:aHW+Z+k9BeEb4HlJJvTs1Sw6Trs1p/MW5Pf0svEeFg8=,tag:0bVlNW/uT+4nsN/XceZMLQ==,type:str]
    gjz010-nixos-server:
        gjz010: ENC[AES256_GCM,data:NFjSrHaj+bKkRlHwmZZ2oq+z63AvSMA85vxqMqEtFulTRrxZbBcRQjJAx4GDLLOyADUOoq7ytfAj9cagNU++TGgKEwatD/5wbA==,iv:o7m+R2U/r43r0qPwIOtDpZV/lrXMtOAltlufsgfvrrQ=,tag:1uO4yfoC2ea0fKEV7PSgAg==,type:str]
    nixos-desktop:
        gjz010: ENC[AES256_GCM,data:RyYUiYvyv7jZ8M7yA1mNPSGhHji2DTCxk2l/Dbr8I/Y1+mufFHZUaSg4PDsaAxzB/cblw1Ob+m0CDP62b43XDMQCB1p3U1g6sQ==,iv:tdiYVcJ3WJuhYUl7CHnNeQpsW47S8HKN4VYuDV8jaA8=,tag:xviG4SkCQC2BAvDJ7ptsFA==,type:str]
    gjz010-nixos-box:
        gjz010: ENC[AES256_GCM,data:ovPo0MUefHDat/r3oqcgcpBS6j/89WxueOW+5yEu+1VwsOnLos4G3Fr74kofzokwCCN3ra3RIWbR/qPb2RpK3dfjmYjZukMqYA==,iv:tL5ylqb6Mm/XaywgsdtQY04Q2w31z8mXxZEOH4GrEqU=,tag:0zKMi3f+AgypLac++N3dLg==,type:str]
    gjz010-nixos-pi:
        gjz010: ENC[AES256_GCM,data:Mnp4HfUvfk9rjnZ9uL4ovPOfvwdeApUqT6Szj4ExlX5eeGy7SgrS3qu5HszGzKq8NTIg38JgPIF33pzvh8P/9IbzAhqTl4rgow==,iv:EGHFdC89zxhIMEFSPTPtt5wIMvJaevYcB+3f6vXRMRI=,tag:36PFqHXSQH2q0bFXIttPjA==,type:str]
#ENC[AES256_GCM,data:yqzst8CppA==,iv:k2UumlVv/zfAKwzXV2kblWhsMWuLdnKWzw/2iZYv9eI=,tag:U5m2XgRs+cMDIHFfnk1fLg==,type:comment]
#ENC[AES256_GCM,data:lBK9q0kS6u9J9UKLzzpActDsXR51MnBPypPBvpj+lg6A92jY1XYqYHNOjsjFdniP3sojbZg=,iv:SfXyanYoHdS+YbI0Yxj3Uho7yCrsrua0v12e0yVZ0l8=,tag:uYN0q3cK3WWv3y4m+5lc5Q==,type:comment]
#ENC[AES256_GCM,data:KCFTMa0qtuJZFw==,iv:xQJvQo7aTOiFLIvMZU2/gVNSJRXRLt7jYuMy9O6ToJg=,tag:v5loYxvk5PYUCqqMAOBQmQ==,type:comment]
#ENC[AES256_GCM,data:D1GG+0v5bjiIOKimVg/U547v/7K8ysZ4TrWEBzJ1w06jlg6UWOTboy8YL4gCKvSazTQN,iv:6DeJuFJ8KwCgNsYBAX6Ao4QAT5qvguXhfUpxGcPhrSQ=,tag:SqnquN+CGc0zNWbv16MbxQ==,type:comment]
#ENC[AES256_GCM,data:5Vy+r4DQmOxzp94rYtrGgxAEP6lTfpJMeHibuEsYG8nZk8KAVgWZzU5ZFeCy1hiiVZF1,iv:ymvGt7TjKsBodp9TAkxrqlSHDXPyIHK53d3RdmjMng8=,tag:kjqqK4LtE89mBjIUFWv4sQ==,type:comment]
#ENC[AES256_GCM,data:jPWa0azM5nlmwJIZgZMVO8Fn9QFqd0joHUt4kQdirAhS14bal23JQbgETWvpgbcdgfLc,iv:Caung2mLx2CPBsWQgGCw1ntqIEUBnDDE4cSLIf71Jmo=,tag:uU9KcbWFiTZQEmLTdBe/BQ==,type:comment]
#ENC[AES256_GCM,data:SbHWuYggACxhyIrZyRoien7PYZMyrA==,iv:ACe0L8oi5mm2cCvzPsY6+E7MyMexNBfeu9rraJeBEv0=,tag:h3oHKOWDvs9somHwUafBJg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2gzuu8xsn2xvcqpdmftt8yyjthgrzq0r4uv952d5aj0c7v29cussp8s0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM0lNYmRPeHpOaVpKN0xT
            RERja1RTdXlCU1hOWmtuc2pTNjdmVmdvTEhjCncxMzY0UCtSdkJWNnRleG5VSHNh
            ZHhTMU1hd1U3Q2JKc0ZwWWpDMkVaazQKLS0tIEY0UnVrQkJZZU5kRG1ERkdNeWdK
            eTk1RnhNanVvZmFhZ0pITHY5bGJOdXcKkctdzzhlUfy0T0+hHjsUmTbKED4CdAxW
            zjFSTQgYlpgMLH5F2YrHTdkWULOHg+jR1+8THheeS3tpDshcteyc2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13n42wjj3kvmj3wk7ms3h7wgdsdpj225lyxvlutg5yd9ja5l433wqelpe7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZFFrMGZPS0JnU25HYlFL
            eGNQVUZtS0EzT2ZiZnBZYU13Ynk2S0xORldVCm1xMllyK1gvTDNyZXpYR1BtWDBv
            VENFckluaWN4WFlIRjR5ZzNzQmNRNFUKLS0tIEJuYS9rdXpubTkyNk4vMjhWdGRa
            ZWRpc3QybzlqVDl6MEhWdHkrUUVtaU0KfJXqwYmHC47vgVoz4Qs6qqynsUHlDqID
            Ttc417aQNdzf6VzacLBBSTYQaUqpFybAbcTvLz8pbwIhSsMcmRiNug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vgcerrxut6mxwm249x6yagz9j9y86pq4csunnp3f6sc52c62yuzsdqpvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaU1rYnBhVWJwT2JDa3lr
            L1hoQXFjVEJybFUwSUYwajZuYzBtT3pqSWlFCjdIOWFZb1VnTjFuSkEvWWxBOVNF
            TUQralBrZlVocVk5d055VVpKNE05TlUKLS0tIGRzd0tQak9FVlludk40S3pwWlRR
            YkxMWnpWTnpuZUtLOXYxN096cndwMVUK1QbVb8lUqX9AJolN9xCv8q0EZoUxZZdG
            4SjQlzeG4SIg9yR9qb7SRBuuAv7LBRB5GRKRQpa9mpQ6+mj5qeyBUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1velfazv9dlx4jqkanmcjv4hf6x6twxjme7n83nvym22txyscmssscjusar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZnVqdm9zNjE5QUZicWU2
            OEMyVEFXQWRtMnVJTzcyQjExWU9wMGdUVURJCkRUN0xuZ2xFVlU5TC9jMHpXejhT
            aG1JbEIvaGp2K01pR1ljSU1ONVFwaDAKLS0tIHdtRkdNQndhNkxMZkpXNktqamZG
            MDhnanZhbnpVY2hvWm1ZeWJINVA4cFkKebCQOUnNlgCItFFqDRU2BR3lFDqGcsEe
            nnkSwQ8ZmIBhSfX3wxQx80VE+tHvMjclUUK/gs2Ni4nR9/4tlFPJXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s7awqlufm0r3cj5wfhympp683aqr6t8zpfpsyxvs8vdpyh8ypxs2wh0jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraHgyd0lBNXB0TStxUHps
            b2lNS2tBVU5neE16d21pTEpERWpmVUJDRDJVCldnbHZsU1NiUDBwZG8vV3dkZzB2
            M2RoQWJUK2NKWUszMGlkaW8yd3dnazQKLS0tIFc0eVZ3aU5TVS9WemhsYllab2Fn
            T1RCVFFkcG52Qm8zZ2tab21aMXExdk0KRXM0NijFAeJcCsIp9pjTGdITfF23FuU1
            w40baokFp3QLxzLRnn+jvBebbZUcmki+KhXYo+lsJ8cf4Qr79tkqIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13jmg2t7nxng36x0xqq5dvst0k9v55q733pu9w8z9xfvp9d2q33xqe4vj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTTNBUUVGSzVzb3htQlJl
            N2NCbEE2LzBCc0ErVGk1WHlRSkQrd0xJSG5vCjhwUENGMm1sOGFrNWtBc2t2Y2xw
            Q2I5eXlKMUdvQlRjZDEzU0drVVFzM1UKLS0tIHh1Zm9JTGlFYndKZXI5Nk8zUWVG
            NG5TRWlvNGFKbjgxc3N2VGJMS1FaRFkKYdNRZJ5wkFn5FVlSuNZRBQsvc99o2+Yo
            ZDdMmmm8TKGwZbs3/mRIYqNsjbkGZjb+u26oyGLOA7DmaUdwnHnelQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12fa2tnhpsntzy6qe9g2ugxvje26nmg6v7ekgr6wymkmjyytrhqnqxwa980
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaEY1SzFHMjlrcjNkdWdq
            cFkwZC90dlFmRkZyNVZ4bTI2QWxLWHp2R1VVCkxya1dEeDVZNWsrZXgwdDZVdWt1
            WUZXRWR6aWdBSVFobktCR3RicWd1TkkKLS0tIHJieG93cmhXbWRTMWliSkptZkdk
            citkNEthRyszR0RubUNXS29XdHdnclUK4LuDF5Ke/FneRxSWvBPXSDgMH2u+KuOx
            wAjD3YhTffDc4ILDlp6ADcO/w/IqaRWuqHSpHGwd+GmxxW17Dxt9zQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nd74ktldahmyq9x8ycc4d6em37csgp4mfm84rk87vsmxxd7d6ydqalv8v4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYndRejRjejZnaUpYSG9x
            YTB3YTlPeXNjOE4zMmk4Z1hveFRyTTFYOVVBCnVGTXNpTWw1TkVYSm1TbnljUUJu
            OTlpL0JramwvUGRtRDZmUXhkbTBZNDAKLS0tIEJXaWRaV2ZNVDFEM2ZCWmtJTlpE
            Tk9pMUdSL2NGR3pDOE80MTQvLzJiZkkKT90PPeflibIIzwjZ03Mb9uQnAU3+LznW
            V0iygtfaIlJgSeXbTgVvtQGDZWvCo/31F1dH6xpqlyIRhxamoHgWEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qrvxhwk50zkas9u06cauxlhtwn2hh9cj878nl0u8aae64pkmdves4r8dwz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZi9FMUxhaFpCb3Fmd3ox
            OSs0L0VHZVA3dVdvWXZaek1OQU8xSWpwbjJJClJzNmZKS2JYaGtsYkUwaG9Jd0xP
            eVVXUDFXa0xTN3djc2NDeTdZcTZqWlEKLS0tIFF3dE94aDR1dEV5WVZqMTZhUmdU
            bWpYaG5CZERqYjVyYkk1SzJOQ2J4SDAK8iEOe2KUut/tmMSCSDgiYH8JeNnlmewE
            8acP4KOdMMcjKLLIaCw7BXz/3Bi7c3+GdjY8/Iot5/KULpTOxFfIBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wl8npxnyfd6vllvheqqgt9fqygerczrpmfsnlp7w7x2lemfd9f5qzltda4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WTRKa0Z1WjRZdnhhcEY5
            MUprNzZ1dmhicG9XR1RZeGpnemZ4QlpLSHh3CkkycXVkVC9kTXZKeDJDbUJLNmxn
            OUtaRnRWNHBrT3Y2UnRycjFiRDg1aFEKLS0tIEp3VVJwakt1V3hIMk1jbjRFYzRk
            L3VoeVQrMjFFcFZtWFh3ODNYNXJXRzgKSfgqs6n/c8r1bFmrrpJojxqk3OA38FQC
            GQaM/hpmYXK/5zao/EvHPwkVYGIsYKmxs8P29zfkEZKLoHNNDkO/sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jjzm9y562w3yajyuccn8ykgac0qsd5jarulgreqxtht3kx2jw37sv48zfh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cHMxVm1GanVJUXlyNjlJ
            VWpsRmE0WTFHZWk2d21HeHpKclZCV0J4VjBBCnpuS2JuZ0hkQllrWE1FSENwNW9j
            VlB4Z2I1VDFqb214c0N5bHFTZGh1TEUKLS0tIFhiNmw5VGIvY1hxNjNydWdXMmQw
            M21aSFgzRlFVQWVkVmtkbFd3NWxGSWcKrZJ/mE7ydDXQVVO43cE3DAp+Kwx4h9Np
            axquzHR9FqApRfrmRbuaxUTWEXg1SDilR5ZbeJ36CNqjGyLATaitoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17qtkl0apngrggynk6dg6jag6hvgkud7l03em0qrwy9j7ev2hha6qenxrar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeXUyc0hKTTJUbkRoYzZn
            REY5dVR6NGhTN0UwWEdGQytyL05YL0RPb1NNCjNTRGhBbk1hQTBQM0w1OGswMTc4
            MFNaZVd3OXJoVkNMK0R4ZlBGYm1weEEKLS0tIGF4QnFiNHVUUWMwdDRrSUFjWDZr
            TXQvVVF3d2ZpZ25GWFBaYUxiZkhZc1EKMbyNjLSS1w+bFwJOTCHtMbmzAGzCLOEf
            beNHqo9HB5MPL2y09eJY82MwiqqY2bUBIuElfxKhPMvtflvfNSCm8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-19T14:22:47Z"
    mac: ENC[AES256_GCM,data:FRL/H0CQYJeQeV533Uh2c4WqSiOotGV4jSD4QbEy1SMYvD37QfS1r0/Vti8M/pVw4XtsEYt5IIgl5E3TLrnDxQF5h86LMxweG6Zu8FE4/iZOlNxIKB5JPCroAkFZYJjSl13a7LTxK46T4CEqPEwLJur7TojLq/4qD2xw2gfuJzU=,iv:lnnf0CPZ584QtIWUDzHnDVkI4nyMKVYFBzT32RuClvE=,tag:JBipWQdOOHml58nRBnoW3g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
