shadow:
    gjz010-nixos-wsl:
        gjz010: ENC[AES256_GCM,data:BhnnYikPDJ7fWyTkInQ6VMxdGH+iuTlprXpQGyRJeortNLXhwkgF14Oa9rlCd1Qs4bfxbVgfrHQIr6letkR9+yS3sqmhBVE6rw==,iv:wqZwRwJ7Rk8Dn3g2m04pVBlZH5cybKjgShPqdsfFBA0=,tag:/lNo9HpkbBZBMUjOKejkDQ==,type:str]
    nixos-laptop:
        gjz010: ENC[AES256_GCM,data:+cUTKdfopdPa0jy34KOS+IiHv7CXSBovFNArkQ6bZt+Xgam8bLPVOgOS4g0cD8x2S/1P4kX9cjyF4FbveSBSr75Cy4IMCc2VmA==,iv:aHW+Z+k9BeEb4HlJJvTs1Sw6Trs1p/MW5Pf0svEeFg8=,tag:0bVlNW/uT+4nsN/XceZMLQ==,type:str]
    gjz010-nixos-server:
        gjz010: ENC[AES256_GCM,data:NFjSrHaj+bKkRlHwmZZ2oq+z63AvSMA85vxqMqEtFulTRrxZbBcRQjJAx4GDLLOyADUOoq7ytfAj9cagNU++TGgKEwatD/5wbA==,iv:o7m+R2U/r43r0qPwIOtDpZV/lrXMtOAltlufsgfvrrQ=,tag:1uO4yfoC2ea0fKEV7PSgAg==,type:str]
    nixos-desktop:
        gjz010: ENC[AES256_GCM,data:RyYUiYvyv7jZ8M7yA1mNPSGhHji2DTCxk2l/Dbr8I/Y1+mufFHZUaSg4PDsaAxzB/cblw1Ob+m0CDP62b43XDMQCB1p3U1g6sQ==,iv:tdiYVcJ3WJuhYUl7CHnNeQpsW47S8HKN4VYuDV8jaA8=,tag:xviG4SkCQC2BAvDJ7ptsFA==,type:str]
    gjz010-nixos-box:
        gjz010: ENC[AES256_GCM,data:ovPo0MUefHDat/r3oqcgcpBS6j/89WxueOW+5yEu+1VwsOnLos4G3Fr74kofzokwCCN3ra3RIWbR/qPb2RpK3dfjmYjZukMqYA==,iv:tL5ylqb6Mm/XaywgsdtQY04Q2w31z8mXxZEOH4GrEqU=,tag:0zKMi3f+AgypLac++N3dLg==,type:str]
    gjz010-nixos-pi:
        gjz010: ENC[AES256_GCM,data:Mnp4HfUvfk9rjnZ9uL4ovPOfvwdeApUqT6Szj4ExlX5eeGy7SgrS3qu5HszGzKq8NTIg38JgPIF33pzvh8P/9IbzAhqTl4rgow==,iv:EGHFdC89zxhIMEFSPTPtt5wIMvJaevYcB+3f6vXRMRI=,tag:36PFqHXSQH2q0bFXIttPjA==,type:str]
    gjz010-nixos-miniserver-fr:
        gjz010: ENC[AES256_GCM,data:qNXfqskxjuD+LnN8mbK0ndtnccFggbKkXMKnIOigEJIMrROZRjslR/WjiQpcirwXT76qgXKm3aVE3JdonZl7JuTVPoJPL7GqcA==,iv:dNjGHqjNwzeS47esuT9CU/fPvNC1oT3XjltDFvRjvsA=,tag:L++jnJTTQ2hFJZxIGkH8lg==,type:str]
    gjz010-nixos-miniserver-cn:
        gjz010: ENC[AES256_GCM,data:wRiD5MOT+fAE5/A4xtabp0NNU5d4BR5FSMn/A8dHg7DJWm7zMbYz7V2Q7B3CVtymCKaBwg4FuzwWGSJE2reKayIUj9ey2g/4aw==,iv:T/3pawLaoEpN2fK0lz/jvJpMnSWSS1UNh8FQYBA2SxI=,tag:3xLACkgr1ugAcjeHL7z8Mw==,type:str]
#ENC[AES256_GCM,data:yqzst8CppA==,iv:k2UumlVv/zfAKwzXV2kblWhsMWuLdnKWzw/2iZYv9eI=,tag:U5m2XgRs+cMDIHFfnk1fLg==,type:comment]
#ENC[AES256_GCM,data:lBK9q0kS6u9J9UKLzzpActDsXR51MnBPypPBvpj+lg6A92jY1XYqYHNOjsjFdniP3sojbZg=,iv:SfXyanYoHdS+YbI0Yxj3Uho7yCrsrua0v12e0yVZ0l8=,tag:uYN0q3cK3WWv3y4m+5lc5Q==,type:comment]
#ENC[AES256_GCM,data:KCFTMa0qtuJZFw==,iv:xQJvQo7aTOiFLIvMZU2/gVNSJRXRLt7jYuMy9O6ToJg=,tag:v5loYxvk5PYUCqqMAOBQmQ==,type:comment]
#ENC[AES256_GCM,data:D1GG+0v5bjiIOKimVg/U547v/7K8ysZ4TrWEBzJ1w06jlg6UWOTboy8YL4gCKvSazTQN,iv:6DeJuFJ8KwCgNsYBAX6Ao4QAT5qvguXhfUpxGcPhrSQ=,tag:SqnquN+CGc0zNWbv16MbxQ==,type:comment]
#ENC[AES256_GCM,data:5Vy+r4DQmOxzp94rYtrGgxAEP6lTfpJMeHibuEsYG8nZk8KAVgWZzU5ZFeCy1hiiVZF1,iv:ymvGt7TjKsBodp9TAkxrqlSHDXPyIHK53d3RdmjMng8=,tag:kjqqK4LtE89mBjIUFWv4sQ==,type:comment]
#ENC[AES256_GCM,data:jPWa0azM5nlmwJIZgZMVO8Fn9QFqd0joHUt4kQdirAhS14bal23JQbgETWvpgbcdgfLc,iv:Caung2mLx2CPBsWQgGCw1ntqIEUBnDDE4cSLIf71Jmo=,tag:uU9KcbWFiTZQEmLTdBe/BQ==,type:comment]
#ENC[AES256_GCM,data:SbHWuYggACxhyIrZyRoien7PYZMyrA==,iv:ACe0L8oi5mm2cCvzPsY6+E7MyMexNBfeu9rraJeBEv0=,tag:h3oHKOWDvs9somHwUafBJg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2gzuu8xsn2xvcqpdmftt8yyjthgrzq0r4uv952d5aj0c7v29cussp8s0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQXhyRGc3NmJ0cUZoOGcv
            NFhPSTlER01JUzRpVG41M3RiVXpPOW40SVEwCnNpWXFaOUVYQkhoOFZKbCtjbnEv
            REhHZ2hzZncvOVA2Qi8yS1RpWG0zMmcKLS0tIE0rakNYR280TTRwL3dFSko5OWRi
            RUlXMW96d25Hbzc1UUl0ZW5ib3NxbmMKFUKpJ3wdIdu2EbPKWsWzIrA+DfSKLXNo
            dtF+tj0+PTvvzBZBCVU3zdeICtlczjFoRl1HbG+rdS6bPJd/LLtfoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13n42wjj3kvmj3wk7ms3h7wgdsdpj225lyxvlutg5yd9ja5l433wqelpe7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTnlZcXMwL0pZMzdRd2hG
            aDQ3dDU2UzEybHdSeEdsVWZsVkdFdUcwazFFCk5Hd1RKK2gxOTQvMVkxdjlhdlc1
            bURQV00rbzV2U0hFNEMvSDdwazExYjQKLS0tIDhOeHNLSlJXNmFSMmRGQWhYOFha
            bm1yTHlpRGhmT2NDZkU2SGNUS2dhdEEKdndewkFZKjxQkZqcFWGck2c1Cm4e6z+L
            JirBOzDcaq0SKQOcw59tkPeYmQmbJ53aV7IcQa6FR5l8A4zOnV9exw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vgcerrxut6mxwm249x6yagz9j9y86pq4csunnp3f6sc52c62yuzsdqpvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdGpqbFNhcVRCV2JiRTNW
            M2hjby9mV0pwakozZzJuZ2pQQ081MXFoWGtJCmd2SlNzVlRuOUxDNWhIcWFWZ1lK
            SlRaNXZwZ2ZSVTd2MU5zWWIwdkp4U2cKLS0tIExJbk0zaEVhQ21YM3dzcStMbVMz
            Nk16MnI5dVpDVWdyRjNVNEVjRzhhczgK/grL1d9Kr21CtEmZuuJNYOlsKkKricct
            Xcu4cschHLLpm1o6/+h14QWBnJqymni4OOa0B3gU0XXsxlaJJZBbHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1velfazv9dlx4jqkanmcjv4hf6x6twxjme7n83nvym22txyscmssscjusar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQzJ1Q2xvNFFDRGh4eVJi
            L3kzVDE1blFIS1NRT3JFL2pWVWIwcGxDdXdrCnM1STZudFE3Sm92NlNzckFQSHhB
            SC9CNU5HVGpXajZCcndUVVRBbjFMaFUKLS0tIEVjcFZlWkYwcXU4SU9seHdPOUhS
            TDBJUksweWxnQWhJd3V1dERQdG9UU3MKa/7GWupGCvK5mFvS43xEmWnPmYMvRoUh
            SZeSAjO2jqXGFfeUyg2Twiw9xczOLaovnnQIo4WJ+cwNC3z2Oj2X3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s7awqlufm0r3cj5wfhympp683aqr6t8zpfpsyxvs8vdpyh8ypxs2wh0jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Skl4bklZdkVaY1hVVGEw
            eG8wSGlERHhqM3ZIOGFmV2crNmFsaTJwcXdNCjVYRmRYek1vVWpMNkszV2QxRmh3
            U05Za1FIQ1J4SFM1a2I1T09UNGYzN1UKLS0tIHlVM2VHcm41ckhBMWZQemdDV1Ay
            VUZLNDRRbm5nbFNFbWgwTkJwSUlCMHMK4w64AszAIzuUapmN2KLcUDXFV3cca/+6
            C/l01AWqfBatq+8Cm7dd94LlXBpJRnOiwDpTsX331ptQQIUzF46xPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13jmg2t7nxng36x0xqq5dvst0k9v55q733pu9w8z9xfvp9d2q33xqe4vj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVlNsT25iYUtodkdKTU52
            RHNlaXVjaHB4NWVBRGF2eUZpQjIrR2hzc244CnZQUFJNdG4wSm1KOXF3V2Ftb2Fr
            bk40d3JTY2VGMHFWMkxLUEdQd3ZYNTgKLS0tIDRRT2w2cWlmNm9WTzVxRUZ1S3Zz
            REFmZkJPeUdyYjNBWVNOOTc4Y1RpRHMKysiZpESuDWcKbsA1su5HA7Lh/xow9+Ri
            xFFFTZHFfDVxmvWK86fPoy9kBNHlUhXl8EYjnT0EdfaukKxMOCslzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12fa2tnhpsntzy6qe9g2ugxvje26nmg6v7ekgr6wymkmjyytrhqnqxwa980
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMHF0SUpDZ1BHbER2WEZy
            aE1tcFF0Yktta3VMd1NIbTJWcUlDN0ZTM0c4ClR1YWZiM3ZpMGVrNlFwMXBoUUFY
            VjcyWEZCbitVNEwreDNFdkFsb3ZFdlkKLS0tIFBWdkNSc2VFZElUK3owNDhFSlFE
            S3hnekNma3lnMC9rbEN4R2QzaDJuZmsK2BJZNjCtzdguBMxbcrNqA67L7F0JNpSw
            wYf14A1ljOkFklZYZxPu3maeSTHEN/JTI3+jHwmGmdtq9TayUZN6GA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nd74ktldahmyq9x8ycc4d6em37csgp4mfm84rk87vsmxxd7d6ydqalv8v4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTWJib1dUb0JTVEk4dDJF
            N0JieEJRR3N3QlpEYkhHeEZYSUlTSGJDcEJFClRaM0pLSHhMNW1LSXptSG94SCtR
            NEh6TWgyVzBRS3M3SzBJUDFxa0ErQlEKLS0tIGJwc0JNV3l6ejViR3BLdm1BVDF0
            UFFGbDNyWlFLSk5ZZlBjRUpYemhLWFkK8aSPzJyHGeBdpLCYSJiL9z0lU4c2mm/g
            +Cy1JgsIenv/zX9hGLSntiF1iRu+SQA2dwUEHMVgRu2c8/XtAacUaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qrvxhwk50zkas9u06cauxlhtwn2hh9cj878nl0u8aae64pkmdves4r8dwz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVXcweXpKWUoxRURZSWk5
            T1NuS25EbG1NN21xdFlHWlBnRFhia042YTNBCkJlcWMzUitBOVFXcENxU3hlNTF4
            WU56TlhKY0tqR2F2UzJVQ3V3UzdzWmMKLS0tIGVRd0RXZnFVTEtFQjZWOVdGY240
            QnRpOVJIZEwvenlYQWpHRGtKUW5pKzgK6pymiiPmie1dGnJCmq33kavEu9a24kzN
            dDI7mg8n4ebLx4zVdlnTqYbJohh1LdcdoIXP/nwHAKK8c01LBm1BtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wl8npxnyfd6vllvheqqgt9fqygerczrpmfsnlp7w7x2lemfd9f5qzltda4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YWJIUUZDZ1JITERidHFw
            c0gwMGY0bklnZFI0ekl6bHAvS0VvT3pYenowCmxNUlNjakUvRkQxUk9QUlBkK2tI
            NXprejV4ZGl5cXlKVmtVRXZnQmpWRk0KLS0tIEU3MjhkV01LMDcyb050UDYzNUtv
            VWVwREk1WDdaSk1weW1RNDNWRzlBQlEKyK+zFXEFuk45aHY2sjZ5pjbOjTsIyzvV
            68GKRnGANtRr2kD5vBqq2+Tjd46XtfVH3syb8dg0/HZFlm6zSddRyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jjzm9y562w3yajyuccn8ykgac0qsd5jarulgreqxtht3kx2jw37sv48zfh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZmtlK2k5NnNBUy9OYnk1
            dkVpOE12bGs2Q21UaFcwaVQrcGJSUWFySFFrCjNIM0FNbkpVVTFtT25JWHBrZlVG
            SkF1Yk12L2dvNTZWTEJzTGFHWGpnR1EKLS0tIGVTY082c3ovaGJ0eExwUmRwSWMz
            a2ZvMEhDbkUwUDF6NzZQMDJ3UFhEREkKkjHyDOFypf9kriknmbkEwwLr6fHiox86
            +lH6XpjEv9RxSKpdJdvZM0UOB+ZwmBJY4QGf4Kt+XsVf+A6aBxUtGQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17qtkl0apngrggynk6dg6jag6hvgkud7l03em0qrwy9j7ev2hha6qenxrar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TkE5eGxITVF4WEtwbUdi
            TzRlZE5TVzBGRDBSRFlITGlCaVNraTE4QTJvCmZxZ0R4cllZamJ0WGRzODBEY0o4
            WmR5YjJGQ21xRjdraXV5QUd3TEl6Q1UKLS0tIGxWQkNMc2twTUpWSTE5bm80OGd3
            UlExbDJZRVdoeXJyRGRNR2RIMjdwdHMKl+BEzpa/6CqkVM31XXX3EqbGT5J8x73x
            DUMlTq1+QvZmFzQX34iJEHqdVfkBkjUCHkKhuNqiEXcT38SRwF1b8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xsmhk62kql4j9hjvs0vgs86fx43husegddfzzegsvlaryu3kqssqx970z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYW1rbWMzSU9vWEFLaUs1
            dElaQ1h3M2FjZTRhRlZKS2Q3L05LU1QweUFBCjQ0Rm5xbVNXMzBBcVEvUFVQV05p
            alpBeUJWMUZnS3gyYkhHdTd2YlJlWFUKLS0tIFlCalM1bWJ1cmRsMysyRllJNGZa
            bEQ4NUt3czhzWHZLMk9yR1dFdDhDVkEKhTtTgYyJSJ//HPCsKBkMOBVSBo6AnoyN
            wNfj2KfGkpkwKwZ4ZBzWoIb2bmFv8dye66DUtcO4uMk2NlK7uWoh2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rf90y55dd3zrtqnvuasppllrglszm3lte5ffrd2l7crqezxg0gms0rzlnh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRE41OUgwZWprZXlHNmNo
            aXR4NE5jTElRT0ZQWTZXbCtIaG1iU2N2LzNJCjRTem5MY2o4ZFJjQzMxZ3ZHZThW
            cExLd2dkZ3ZHaGp6eTdmMEhta3o3aFEKLS0tIE9YeFRzc3JKRmxSUktRWStKMS84
            MWliLzRtMnBYZExNSjZxUWo3TGtUTHMKvEGuy1DpU8BJP5R5P/1exx6MBvKxbFSn
            g2xwdY6I03HFPbMkXo1hhOnbKEzr3Gw3Ub04ub9f6rA3/G0OaRjCAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T07:55:26Z"
    mac: ENC[AES256_GCM,data:arrKSEHdNPUupdZKhswxN29BlnleRdpcaDS9exCsj/P5lI4+bXiBlv6ynECHbIvJygOURwdcqskv62lbjXdyx9ENqdbo4L7AP9uVIRsp4jgdhXOptdFWhN5PYJiGe69wmrYyphwS3U+kfijKKDRx31xvinPs3Ib8jLPu8cl9+dg=,iv:KH7GRaG68uNP6tKV2t4mGdRQ87dAxT2pxVH7X2GAN0M=,tag:q5ew4SRbBs8AXttiTnEsDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
