shadow:
    gjz010-nixos-wsl:
        gjz010: ENC[AES256_GCM,data:BhnnYikPDJ7fWyTkInQ6VMxdGH+iuTlprXpQGyRJeortNLXhwkgF14Oa9rlCd1Qs4bfxbVgfrHQIr6letkR9+yS3sqmhBVE6rw==,iv:wqZwRwJ7Rk8Dn3g2m04pVBlZH5cybKjgShPqdsfFBA0=,tag:/lNo9HpkbBZBMUjOKejkDQ==,type:str]
    nixos-laptop:
        gjz010: ENC[AES256_GCM,data:+cUTKdfopdPa0jy34KOS+IiHv7CXSBovFNArkQ6bZt+Xgam8bLPVOgOS4g0cD8x2S/1P4kX9cjyF4FbveSBSr75Cy4IMCc2VmA==,iv:aHW+Z+k9BeEb4HlJJvTs1Sw6Trs1p/MW5Pf0svEeFg8=,tag:0bVlNW/uT+4nsN/XceZMLQ==,type:str]
    gjz010-nixos-server:
        gjz010: ENC[AES256_GCM,data:NFjSrHaj+bKkRlHwmZZ2oq+z63AvSMA85vxqMqEtFulTRrxZbBcRQjJAx4GDLLOyADUOoq7ytfAj9cagNU++TGgKEwatD/5wbA==,iv:o7m+R2U/r43r0qPwIOtDpZV/lrXMtOAltlufsgfvrrQ=,tag:1uO4yfoC2ea0fKEV7PSgAg==,type:str]
    nixos-desktop:
        gjz010: ENC[AES256_GCM,data:RyYUiYvyv7jZ8M7yA1mNPSGhHji2DTCxk2l/Dbr8I/Y1+mufFHZUaSg4PDsaAxzB/cblw1Ob+m0CDP62b43XDMQCB1p3U1g6sQ==,iv:tdiYVcJ3WJuhYUl7CHnNeQpsW47S8HKN4VYuDV8jaA8=,tag:xviG4SkCQC2BAvDJ7ptsFA==,type:str]
    gjz010-nixos-box:
        gjz010: ENC[AES256_GCM,data:ovPo0MUefHDat/r3oqcgcpBS6j/89WxueOW+5yEu+1VwsOnLos4G3Fr74kofzokwCCN3ra3RIWbR/qPb2RpK3dfjmYjZukMqYA==,iv:tL5ylqb6Mm/XaywgsdtQY04Q2w31z8mXxZEOH4GrEqU=,tag:0zKMi3f+AgypLac++N3dLg==,type:str]
    gjz010-nixos-pi:
        gjz010: ENC[AES256_GCM,data:Mnp4HfUvfk9rjnZ9uL4ovPOfvwdeApUqT6Szj4ExlX5eeGy7SgrS3qu5HszGzKq8NTIg38JgPIF33pzvh8P/9IbzAhqTl4rgow==,iv:EGHFdC89zxhIMEFSPTPtt5wIMvJaevYcB+3f6vXRMRI=,tag:36PFqHXSQH2q0bFXIttPjA==,type:str]
    gjz010-nixos-miniserver-fr:
        gjz010: ENC[AES256_GCM,data:qNXfqskxjuD+LnN8mbK0ndtnccFggbKkXMKnIOigEJIMrROZRjslR/WjiQpcirwXT76qgXKm3aVE3JdonZl7JuTVPoJPL7GqcA==,iv:dNjGHqjNwzeS47esuT9CU/fPvNC1oT3XjltDFvRjvsA=,tag:L++jnJTTQ2hFJZxIGkH8lg==,type:str]
    gjz010-nixos-miniserver-cn:
        gjz010: ENC[AES256_GCM,data:wRiD5MOT+fAE5/A4xtabp0NNU5d4BR5FSMn/A8dHg7DJWm7zMbYz7V2Q7B3CVtymCKaBwg4FuzwWGSJE2reKayIUj9ey2g/4aw==,iv:T/3pawLaoEpN2fK0lz/jvJpMnSWSS1UNh8FQYBA2SxI=,tag:3xLACkgr1ugAcjeHL7z8Mw==,type:str]
    gjz010-nixos-laptop-mechrevo:
        gjz010: ENC[AES256_GCM,data:mOOCm0s/39Jgj4slEtvxYg9nZ/EaSDVua5atxF2fuyQEPVUi9wlxmYfNqZ9ZZOYAbwq1h7oLEDmx1yxMWhu1HHUxyuVjgGO3gQ==,iv:PvAAQZy71bBsQozUXmU1yCtArQL9wpGJDFAM2OtNnFs=,tag:xcB6U3npkJt+34hu+U666Q==,type:str]
#ENC[AES256_GCM,data:yqzst8CppA==,iv:k2UumlVv/zfAKwzXV2kblWhsMWuLdnKWzw/2iZYv9eI=,tag:U5m2XgRs+cMDIHFfnk1fLg==,type:comment]
#ENC[AES256_GCM,data:lBK9q0kS6u9J9UKLzzpActDsXR51MnBPypPBvpj+lg6A92jY1XYqYHNOjsjFdniP3sojbZg=,iv:SfXyanYoHdS+YbI0Yxj3Uho7yCrsrua0v12e0yVZ0l8=,tag:uYN0q3cK3WWv3y4m+5lc5Q==,type:comment]
#ENC[AES256_GCM,data:KCFTMa0qtuJZFw==,iv:xQJvQo7aTOiFLIvMZU2/gVNSJRXRLt7jYuMy9O6ToJg=,tag:v5loYxvk5PYUCqqMAOBQmQ==,type:comment]
#ENC[AES256_GCM,data:D1GG+0v5bjiIOKimVg/U547v/7K8ysZ4TrWEBzJ1w06jlg6UWOTboy8YL4gCKvSazTQN,iv:6DeJuFJ8KwCgNsYBAX6Ao4QAT5qvguXhfUpxGcPhrSQ=,tag:SqnquN+CGc0zNWbv16MbxQ==,type:comment]
#ENC[AES256_GCM,data:5Vy+r4DQmOxzp94rYtrGgxAEP6lTfpJMeHibuEsYG8nZk8KAVgWZzU5ZFeCy1hiiVZF1,iv:ymvGt7TjKsBodp9TAkxrqlSHDXPyIHK53d3RdmjMng8=,tag:kjqqK4LtE89mBjIUFWv4sQ==,type:comment]
#ENC[AES256_GCM,data:jPWa0azM5nlmwJIZgZMVO8Fn9QFqd0joHUt4kQdirAhS14bal23JQbgETWvpgbcdgfLc,iv:Caung2mLx2CPBsWQgGCw1ntqIEUBnDDE4cSLIf71Jmo=,tag:uU9KcbWFiTZQEmLTdBe/BQ==,type:comment]
#ENC[AES256_GCM,data:SbHWuYggACxhyIrZyRoien7PYZMyrA==,iv:ACe0L8oi5mm2cCvzPsY6+E7MyMexNBfeu9rraJeBEv0=,tag:h3oHKOWDvs9somHwUafBJg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2gzuu8xsn2xvcqpdmftt8yyjthgrzq0r4uv952d5aj0c7v29cussp8s0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdTh3TUt5ZDgvQkprSytm
            eDhERUR4RTVyNkp0clNybEFYN0c5WVJTRmdnCjFGUVhsZ3RvUVRybWVxcnk5QTNI
            bVRJT0RuYnlpMWsvcm1UbDYxbHEvRzgKLS0tIEVIZ2ROaHhBNzVTaXFFNUF2dzRL
            dzNwZ1M4R2lPeit6MWtZaUNEVHlVKzgKfFlGDhxHHHU1CDEI7aIZWwYeNfAbnYTh
            +FmCFZf2UUhxKgoHLO9kAyROClSzbdILAU27LT2wA24dcf1x9BP29g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13n42wjj3kvmj3wk7ms3h7wgdsdpj225lyxvlutg5yd9ja5l433wqelpe7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTk9FMDd2OXE5ZkJlYitL
            b3JEbWpjTURRT2Rhb25MaXpQdzZOZGVaY1ZzCkhYbEZtNy94RzdLUlIrSDI1dDF4
            QTBsZEdlZTVwY0Q5eU9jS2xtVkREU00KLS0tIFo3MDk4a041TE9ZWUdpelFGZE9J
            WEdEMTNOSk5LZUhxdUpsY00xNy9FMmcKgmH0u0f8G86CNymP2U/Yhjdrm+yWPnTV
            wf1yNBB89if548zCwxxgT3v4Log/adC2ttl2bbaganvl+CQWDVVsQA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vgcerrxut6mxwm249x6yagz9j9y86pq4csunnp3f6sc52c62yuzsdqpvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Rm9GUDZMVDZLZ1BDbi9a
            V1U4OE93U3d2dzdhK0d1cVdaVTl3MDI0YVFrCml2b3lZNnhrRUxtbFBMM0RiV0dF
            Qmpaekc5YlViSGpDT0xDL2lYSG1lYlEKLS0tIFcyc0x1ZHUrbDI1RUthVUtLdW1E
            aVB4TzBRMitrLzBsVDJJOWlaZFM1bU0Kly1TLeFT7yW1hvPuPCWuYx6zqlkshimu
            303RiShLRMLhwvEL+sU00utff8DLXpoqviR8UbHKY465u5zcezvb1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1velfazv9dlx4jqkanmcjv4hf6x6twxjme7n83nvym22txyscmssscjusar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOGh3RXBjM0ZOZ2FFdE55
            eDhDSUk0OUVOR2IwRm5EbnVGclpJczNXZGxBClhvRlBnd09yUnJaeGgrZTBSOThW
            MUk1aVFEM3ZCVS9MWCtzdFlyRnVlUU0KLS0tIDdMcUc4ZEpHVlFQc284bnBvdlVB
            VFk3YURUZTlEd2RnTWZmeU81SHZDQXcKrMM2f19Q8V557GsUmACu6Ual2bWv8P7H
            XGLDjzZgvJ3+Y/s+UMYbNshmmLVeI18nLe240s2MXyFs6F9LvzyZ6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16s7awqlufm0r3cj5wfhympp683aqr6t8zpfpsyxvs8vdpyh8ypxs2wh0jx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOXM0YWJBOUlVeXB3cTdI
            ZHdmYTRyeGN4WmNZZHgzVUhnZ3JUWVFnUXlNCjN2eWdIRFo5SjBSSGYrdFhKQjJy
            dlQvZ3ZiVHVvbXYvTHpFMm82dGN2WE0KLS0tIC95dnQ4ZzVBZ1lUQmFpVnRkYTVY
            NjlxSWtsTlkwY2JMVGtKTW9ER3ZBQXcK7oscF94CY0SR4aQaoIBuDMLwQ67hhaON
            uD2+zLuU2J1WYeu9RwVO/DgBB2l16ncKDMIMl9aBxHsrxle/GuNE3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13jmg2t7nxng36x0xqq5dvst0k9v55q733pu9w8z9xfvp9d2q33xqe4vj6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRFI5dEZFZGIwM2NhbUFo
            ZzJSKzlrRmxvVXF5TVA3R2dRVCtldkxaRzJjClBPNU5Gb3ZBZUtjREgrL0cya0dy
            akVkOGFHQVNVYkZCcE1aaUtXakJYQkUKLS0tIFRMYkFKK2xyTGN5RmtmS0hvcnZK
            bTRnNjk4RG5HdUJlMFBVUmpldU5Tc3MKXA2t9AKkPmcqoY2JvUF3tNsjgzq0FXi9
            L31RQnZ39kc4SfaTwzPBphJzol0ff/eFRWoutRxjgPyUInC3L/sKtA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12fa2tnhpsntzy6qe9g2ugxvje26nmg6v7ekgr6wymkmjyytrhqnqxwa980
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSmNuZmxHOXIzS1hrTEdo
            SWhlOE1PREtodU9kR0dZdjdCbHd4citwOWdBCjFTMzVmQ3dSYzY3T3RQZUlhL3Vv
            cWx3R2t1bm5HNCtoelk4SnFyZ3ZMUkEKLS0tIERyQnIxdWRiTXhwVzl4dHczWklK
            RzRkYmFlRFV4eUJ4V3g3dDNHSFBCREEKNk8B9Xt439n9vNdytCSfPvpDa0xpL+8k
            gKF/esY2zUoe0Bx+j6eDaePkQDN2LvqcIIlkF37PNx/rAgPfLwG2jg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nd74ktldahmyq9x8ycc4d6em37csgp4mfm84rk87vsmxxd7d6ydqalv8v4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaEViYjQxU2FJT3FNRk1a
            c3ZQbm5PdklMbXhuVFUyaFY0YktpWGkzWWtRCjE3SGNyVU9OZ1JhZUI4emk0UUJu
            TCtQRUs2QXUydElIbER0K3JvSzJ0WDgKLS0tIGpoSWcxWFhRckhBMzlza2RNRWFz
            WnNqb0lPb3plZ0E0TXJJUWRLcGJ5RXMKDkVo0rI1/ads9I4slp4wrk47GiMYRVQG
            0pAjL1RGTRquap9vmlEg97cMpXwwu84JHJQNG7nkTN7zVhD6fKgSIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qrvxhwk50zkas9u06cauxlhtwn2hh9cj878nl0u8aae64pkmdves4r8dwz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUGJ2UXA2QzdseVVybGsy
            WVB4NmpsZ1RKYWFSdFdHNG4wS3hmUmxFQVZrCkR4SFFhYVJ2WGVVUDFySEppbjZW
            dWZFNjZHOU4rR0YzT25pT0NHbVc2dkkKLS0tIGx4UGtCTkVRYUF3NDVkWUQ0QkZq
            TXBkWm1XUVZNT2VNTVZOT1RUQmxoTGcK1EhyfBMNbSo0hUBcUG2UE7+BAQdf0U7V
            6GxyF9g8Y2K7TeTeCHfMMuUTATomltIXMQ4AsIyXmU6jOle+UJ5TYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wl8npxnyfd6vllvheqqgt9fqygerczrpmfsnlp7w7x2lemfd9f5qzltda4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUit0QjhoLzFaT2NwT291
            TGFEZWJycEhaenpwcEFmbytySUNmbmpiTW5vCkJSNmN3ZlE0NFlFZ3crRk1sY0RR
            N0liSU92aXRjWkF5bVArc3ZMQ0dhU1EKLS0tIGcrbnJoL3NqN2JxUlR0b05wSDNi
            Qyt1R013UXlYYThKdEFyMVVPMjkwQTAKnsVcZ/NPGHdEbHXKbXaNhTFQhM8GmnYW
            hBU34R0ApMvJfSbcKm+ldLHY+2DqN7UyhdndCP75hCxh0NawKj1EAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jjzm9y562w3yajyuccn8ykgac0qsd5jarulgreqxtht3kx2jw37sv48zfh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVnZZZk5xSCtPQWZBbldV
            Z2xEcVRGSndVT08wK2JVbnNsVExvS0NnVWtRCjVBYXVpK0I3ek9QUjRYL1dxTUlS
            Ry9LTmlRdGlFTG1ma050MjRWNUVGajgKLS0tIFZEVmVvanlvbHRvUzh2UG9aQ3lI
            VE9zMVhrbHpWaFEvMlZwamNJL1JRTFkK2Hy4aO8FT4yME8oDk29EaFSdVWbqYxBp
            4qqbahSs4uBkAmbuxzsA3DvamLZ5DD3j5QU0x9fy2D/FsyDfu3Pnmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17qtkl0apngrggynk6dg6jag6hvgkud7l03em0qrwy9j7ev2hha6qenxrar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSE92UzVSSVNGOUJNTWt3
            aUFKcWd1Myt5djhxVVZYS3ZRMWEySUZvMENZCjlYMTEvZmt2RmlaK21UeWtXcWdV
            NEI1SERNSzFZTU8xU1ZLRFMyUlNTSEkKLS0tIGk2d2twSHNic3ppR1BWR0VLTkFt
            N0ZVdTBlL2lsTGtVUmNJbmhiYWFFUG8KjRvc3j4SVkyxqT68lgVzFbLuw0oK5Cyu
            5YXg9VBet2RMovtVWHJxkElYf42/0NExF3eAtERyvBZe3dVFudItjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xsmhk62kql4j9hjvs0vgs86fx43husegddfzzegsvlaryu3kqssqx970z4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZT1JmRkRGbG4vWVEwR2Rn
            bUZPYkV2VXNFK0NlZ08zVGR2Y2htRVFmSm5NCjc5dS90M2Zzek9PRGRzT3ExVjVo
            bUJBN0w1MUJ1a0hYYis0dkh3WGZOS1kKLS0tIHVOMk1ZNDJwTkc1d28vNDFJazBB
            Q1lOeC95L0IrZjJLbkg2MFFnTkJzVGcK87Sv2GX3+TXyQQ6a5NrmlPfsHoS+yrTm
            3Z+aYJdWJkPGoX1SQii2HjdAuB7qAEyo66LUhAGECda1TrCLJpw72g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rf90y55dd3zrtqnvuasppllrglszm3lte5ffrd2l7crqezxg0gms0rzlnh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvd2M3YlBxUnk4aWlZcjMw
            YllXSU5HcStIQ1cxL2RFaENIZm11NkZoVkdvCmpzd3liamhJQTE0N1Y2Yzhaa0RJ
            YXFsREg4ZU43dnF4Y1ZCamwrNU5mamMKLS0tIEo4OXVFaXlIYnVFQlRPME5qWUVt
            RlUveDFkYkgzRWdYMWpKMUxqeXBkYmsKKNhi4d35bkAJ7fNcTOYgUXbsrlRHcAJH
            xyiET+X2lJkIQG7pjwx2pP+1SklDD3/tuqYhUAipKdnZ3lMJ1dypEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jg5as6qlfac76ywgffnrzha9jk3drunax8ut25x5m38m6x49ae2sg3rve5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGK0dxb0xGQkN3ejQ4ZHV2
            ZUdxbUR6ZTVTRHE1RjNHWEdCeUwzTFNId0FvCkpwVXlwSlZyTVMwbTRoejg2MmNY
            bDZva3BtWVdEZmI5dmlKK2FJSE8zdUEKLS0tIDVXd0I1a0taMjFYek9iRUhSOE1I
            OWZXbUpraWVudVhodGpnQmNZOEJ5M0kKUkk+bqWBwAihpDBrkbSOMIT1hD9OfOTP
            1pbhEOxU7DnRUlvJqes0l28eKa7YBMzjOVJJzcIN1+nICHFQEzmMFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kd3fxf4fxfjxfrqau0whz6u2rp05dl7evq6qanpzz5zudue4tfvsekwkc8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcXhybVBMZHVObit1N0Vp
            WmVRUWlFUFN3NHhULzZBN3dsT21oVEVST2pNCjFyeHRzMmJkUU8zaGxkQTZuK0tP
            YXAwTVBLWWVCWnRPakFDNmQzNEVHK2cKLS0tIEFyb3hZZmUzWWZOWkw4K3RsVGN6
            ck9xMUVDdDFETEpoM2UrQkEvYUdqZEkK0htt6c5RadmGgjdwkkHWUQFj4TIdAp+5
            TVINYth+xoFD/ktP/aIenYX+lJj9Q5gGa7ljRcxZhi/WVz/5SCT/CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-08T15:55:30Z"
    mac: ENC[AES256_GCM,data:VhNk6CqAZeH7b0vzY0z248e/4DxzjEwja83Zp2IsXvcZOR+3sNjS0BjxmkLYs4eNs1IFl0AOQDNGCQ9o90s8fJBoC2bM9ru6nU7TE0qS66fARlxrraqACnekRDn5od7qPBPlnJs0mX21EZSS7bubeHvztZ+vepS9+GbNUsqrLi0=,iv:q3cHq6CsxR0mMKNNm6nBzaPAw9MaOezl1ZAZkjT6/9E=,tag:d3VtVSSA4Vtz2Vc5DrO7yQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
