shadow:
    gjz010-nixos-wsl:
        gjz010: ENC[AES256_GCM,data:BhnnYikPDJ7fWyTkInQ6VMxdGH+iuTlprXpQGyRJeortNLXhwkgF14Oa9rlCd1Qs4bfxbVgfrHQIr6letkR9+yS3sqmhBVE6rw==,iv:wqZwRwJ7Rk8Dn3g2m04pVBlZH5cybKjgShPqdsfFBA0=,tag:/lNo9HpkbBZBMUjOKejkDQ==,type:str]
    nixos-laptop:
        gjz010: ENC[AES256_GCM,data:+cUTKdfopdPa0jy34KOS+IiHv7CXSBovFNArkQ6bZt+Xgam8bLPVOgOS4g0cD8x2S/1P4kX9cjyF4FbveSBSr75Cy4IMCc2VmA==,iv:aHW+Z+k9BeEb4HlJJvTs1Sw6Trs1p/MW5Pf0svEeFg8=,tag:0bVlNW/uT+4nsN/XceZMLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2gzuu8xsn2xvcqpdmftt8yyjthgrzq0r4uv952d5aj0c7v29cussp8s0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaGpnUlpwc1ZYTE5jRXdU
            SGxvQitXTTg1MXlyeDhGZkRZWmtzT1lXZW5rCjhka05Ua1Rubi9hR2t0UTA2Ulpq
            QjZNSnVXcTFrdExOZ0YvNjJFT3dubVEKLS0tIGZIQUcrVVVLa2h0eE9xbkhBdGRS
            U29FYVY4bjZZUkhWUjIvMVBTM0VBaEEKd6lM+MLtIqYpxg0nJAr/7wf1ScwFz/kQ
            AFkfpdF9RTqKVi9tdMWqjZAbZ2d+UjovDLGQRjgOn/j6ysz7nyMt3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13n42wjj3kvmj3wk7ms3h7wgdsdpj225lyxvlutg5yd9ja5l433wqelpe7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV3J2L0E5cHpZYWxyWE1I
            aC9EMnhmNE1PUUJIWU5YT0gvMUFEQ1pLT0FzCjc0Zy81K3ZHQUt0VVkvc3VoT2dp
            dThwQnZ0QWtvVzB4RnB4V1hPNFlQQUEKLS0tIElmQnRJdXVjKytPeG5vSGszM214
            M1Z0eGN0WUUrV0M3czk4V2ZQY1AwMWcKdoFN2lidAo1UFzgxyvlcwACUOD1Rikr6
            I55Ov3mI/aUhYBFwEZAYLUPTvRe0Fl+gISMUoBd1BkuPEUgYC2h17Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vgcerrxut6mxwm249x6yagz9j9y86pq4csunnp3f6sc52c62yuzsdqpvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UXhTanAyNFovOXRaSUJl
            NlcwbWliSWZ2ZVZmWk1NNEJLSU4xQnVOTERjCkFrdDBRUnNZMDEvWjNEaFFxdktz
            UE9EYlVNRXV6M0FlRUUyL3RmWUFrODgKLS0tIHNEcGJUMGlodHJMcE04bldyUTRN
            U2M1QnNiVVFqMHYxeUtKVENPVGV1VmcKmmxYrsn3vSmQDDC6dYk25MW1VcIKt3bT
            1Bfn2XlW7drttF2S6eLUmvOFVqoXZWvQqeQ/9HI+eBxL1ynbmTwUtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1velfazv9dlx4jqkanmcjv4hf6x6twxjme7n83nvym22txyscmssscjusar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dEl6R2JNdkxpdVlhRWRh
            bVVGRDNsUFhIMUJSR0FPSkYvb3duaEdmZzBFCndRZGtxTmhzYmR0cDhjMFI0Y0Nh
            SlF5cG4xaWczMjlLWEtNNmRvUnR6bXMKLS0tIHVFVmtBcW1KTVBlVFovUnZBeFkr
            T2lSQzNEa2drZTRmSlhiUWRnRTBGNkkKNecZ+poEdqfctBp7IxrLNEwkJ2dU2mOS
            Y/umRlQye6pRYlmQ3nzvkFYiA+4ZEacfPU4oNwmI6M53CoUh07ZDAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-18T10:37:31Z"
    mac: ENC[AES256_GCM,data:aXy9viPIECJ5x91GhwYbTFnVUYZOBtbroWj/OW1z4Xed54y8dwwCx9AW/ed+HJ/M0vw8Tp4SPz2+3vqNz5CH9jGB3/iqywPoT10lW13kO8/Ggs7zGq9vKg40i3LjPZBi6N3IdFfdZz1fiF7ZkmAeS7pzoeQlmMwkds/P7jTJ3qA=,iv:5ZWUWYUvbihEt9x2WUuLBdKvdD8hxN7ECBM/nRLVNjg=,tag:iiloqSc6Zyy7L0sLCvi03A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
