shadow:
    gjz010-nixos-wsl:
        gjz010: ENC[AES256_GCM,data:BhnnYikPDJ7fWyTkInQ6VMxdGH+iuTlprXpQGyRJeortNLXhwkgF14Oa9rlCd1Qs4bfxbVgfrHQIr6letkR9+yS3sqmhBVE6rw==,iv:wqZwRwJ7Rk8Dn3g2m04pVBlZH5cybKjgShPqdsfFBA0=,tag:/lNo9HpkbBZBMUjOKejkDQ==,type:str]
    nixos:
        gjz010: ENC[AES256_GCM,data:v+4O/u6gc8HI8fc52U99uGrKHjoYtoMl9uU8WnZJFsZFPF3P735eT8swOogRkXLybv6GcP3y6Ba+ajrrwz2ufuy/CP14XOsIoQ==,iv:VKTkWSL4a0fos51meY/zEaT3XVI+uNfe9wVcwF3Rg8k=,tag:PokNpFMrdgTA5Jl8dE2HwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q2gzuu8xsn2xvcqpdmftt8yyjthgrzq0r4uv952d5aj0c7v29cussp8s0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSmpUbmhNSTd4dStCem13
            QnNSbXdlS3hRTUlzQ2ZUQStMVUVCaDN5b1V3CkJyYkU5aHJCY0ZzbGRJWDJrWmFY
            SXVySUdaTGlaVWh5UHNBTXhGN2plTmMKLS0tIDhBOGRWRi9PbVU5L2EySFdTL1I0
            MDVwV2VXZlhYcWtDRU5FanRzdDhOd1EKhB+jRGeAq2iTuELJHshk1tbyqKNWkBzL
            kB//d9uu4NGiyIrvqaF+/tTWhTlAEsMFmYNTfFYNsShntpERk+7nDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13n42wjj3kvmj3wk7ms3h7wgdsdpj225lyxvlutg5yd9ja5l433wqelpe7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2U0t0VzVzRzVxQUEwMFJ6
            VjZNd3B2cXpDWFR4QTA1S1F3eWViSFAxS1UwCkxzVDRRNWlJY00rYmhrTHJhak9G
            cVNNWHpOdk8yWGxiVldxeDVqUXoxOUUKLS0tIFd6cm9CTUpoNDh0YWZqYUZ6MGda
            VWdiSTdDNldlT0ZxWndCbDdCRU9FcmsK0HKf51Rd/fdMnnGIEYG7NXVKoNBq9nEG
            sjIRyonOr21TY7aVoltKvKk81aplVzpxss9Cr6iqLlCEPlgvM/UYkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vgcerrxut6mxwm249x6yagz9j9y86pq4csunnp3f6sc52c62yuzsdqpvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWVRRdEZCYzRyVEtFalBX
            UnJZbzdnRG4rVytadE16RXd0S3ZDN2N4azNVCjFCa2lvYnpFNzdmbXYwZHJMWHJu
            M2RVaDBHYnhGSDhWeUJHbDBCOTl2ckkKLS0tIE8wUkxKYWhpdWl5dk5kU2R3QlZr
            RWxjbUl2aFhCazJoMHpNK1lwUkhJbVkK96Rtu5l69lkTiBiyBRIFtAV9Z+gYwXrr
            T/acRYsez5hiLFQBDDgud092DRs6sr5D+iun+o9c/4G+CzbcbvVNrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-18T08:56:01Z"
    mac: ENC[AES256_GCM,data:bH77yS/2zevHvljMgdNn2x+V9EnlrsuI4yo30MfKeaZZMwINBqiKWDG9Jel17oCq3i2wv6zTx3NFoOs7PAhJgBxAdQ1CbVJHFdhQ97a4apX/K/po0MWajNx+t8GYEzKTUyJmCT87O1B5j0RQKHVtJGcdHcdRF4gPHxxCyGEzCvg=,iv:bADc9xulvjp0PLqnA73l6tNIqbVJstp9BEnf4mElFOo=,tag:WoBelqG4NoDCw/OIi1uC2A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
